### ISSUE TITLE
Remove support for Elixir versions < 1.3

### ISSUE THREAD

**Issue by RobertDober** [pragdave/earmark#108]
* Deprecate in 1.1
* Remove in 1.2

**Comment by RobertDober** [comment]
and deprecate Elixir <1.4 (to be removed in 1.3)

**Comment by RobertDober** [comment]
I just removed support for Elixir <1.4 altogether fro master. What do you think @pragdave , is this too harsh?

**Comment by pragdave** [comment]
Not harsh, I don't think.

**Comment by RobertDober** [comment]
Great Elixir is moving fast and supporting 1.4.x and upcoming 1.5 with 3 versions of OTP is what we will do from now on.
