### ISSUE TITLE
Keep README.md in sync with latest version on hex. 

### ISSUE THREAD

**Issue by dummey** [pragdave/earmark#109]
This may be an edge case that doesn't need to be covered, but the current README.md docs uses:
` html_doc = Earmark.as_html!(markdown)` while the latest version on Hex (1.0.3) is still using `to_html`. 

Another option is to fill in the *Dependency* section with a concrete version.

**Comment by ericmj** [comment]
Another option would be to include the readme in the docs. That way hexdocs will have the readme for the latest version on hex and github will have the readme for the development version.

**Comment by RobertDober** [comment]
@dummey no it is not an edge case it could be quite confusing, ty for the report.
@ericmj and adding a note to the README that the relevant version is at hex. Would make life easier.

**Comment by RobertDober** [comment]
@ericmj basically the README are the docs so I went with this simple fix/kludge. But I am open for ideas.
