### ISSUE TITLE
Earmark.to_html nil

### ISSUE THREAD

**Issue by ggerico** [pragdave/earmark#118]
When nil is passed to Earmark.to_html, you got the following error
** (FunctionClauseError) no function clause matching in Earmark.parse/2

You may add a pattern matching this eventuality. 

 stacktrace:
lib/earmark.ex:289: Earmark.parse(nil, %Earmark.Options{breaks: false, code_class_prefix: nil, do_sanitize: nil, do_smartypants: nil, file: "<no file>", footnote_offset: 1
, footnotes: false, gfm: true, line: 1, mapper: &Earmark.pmap/2, pedantic: false, renderer: Earmark.HtmlRenderer, sanitize: false, smartypants: true})

**Comment by RobertDober** [comment]
I fail to see the value of this. Is it common practice to intercept that kind of error message with something different, can you cite some examples? 
IMHO the doc is enough but I am listening.

**Comment by ggerico** [comment]
in phoenix controllers tests, when you pass an empty model to test the route, this error will occur. That's it.
```
test "shows chosen resource", %{conn: conn} do
  post = Repo.insert! %Post{}
  conn = get conn, post_path(conn, :show, post)
  assert html_response(conn, 200) =~ "Show post"
end
```
Here a quick work around I put in the view:
```
  def markdown(nil) do
  ""
  |> Earmark.to_html
  |> raw
  end

  def markdown(body) do
  body
  |> Earmark.to_html
  |> raw
  end
```

**Comment by whatyouhide** [comment]
I think rendering `nil` to `""` is a very application-specific behaviour and I don't think it's something that the library (earmark) should do. As for a better error message, it's not very common to have libraries intercept bad arguments to improve error messages and the most common way to go is just to express the "happy path" (`when is_binary(...)` for example) and let the function call fail with a `FunctionClauseError`. After all, the expected input for `Earmark.to_html/1` is very simple as it's a binary/list of binaries.

Finally, what you have in your view could be replaced by a much shorter version:

```elixir
def markdown(body) do
  (body || "")
  |> Earmark.to_html()
  |> raw()
end
```

if you really expect to pass `nil` to this function often. :) Wdyt?

**Comment by ggerico** [comment]
Yes, it's indeed "very application specific", but Phoenix is quite popular. 
Thanks for the shorter version ~
