### ISSUE TITLE
Feature Idea, feedback: Task Lists in GFM

### ISSUE THREAD

**Issue by brainlid** [pragdave/earmark#126]
I would like the Github flavored markdown feature of "Task Lists" to be supported in Earmark.

* https://help.github.com/articles/basic-writing-and-formatting-syntax/#task-lists
* https://help.github.com/articles/about-task-lists/

I am willing to try implementing it. I am proficient with Elixir. 

I would like:

* to find out how open the project is to receiving it as a PR
* to get an idea of the relative complexity by those familiar with the project
* pointers of where to begin

My interest is in making the simplest implementation possible. Essentially, detecting the `- [ ] text` pattern and making an unchecked checkbox and `- [x] text` for a checked one.

**Comment by brainlid** [comment]
I'm using an alternative approach, so I don't need to create this feature myself now.

**Comment by walterbm** [comment]
@RobertDober I would be willing to work on this feature if the project maintainers think adding Tasks Lists is a good idea.

Some pointers on where to begin would be greatly appreciated though.

**Comment by RobertDober** [comment]
@walterbm It would be a nice feature to have for some applications, however, thinking about Earmark's main job, which is creating exdoc in HTML format, I believe it is not such a great idea.

Firstly, we would break backwards compatibility, and secondly task lists are not used in Elixir code documentation very often ;).

We also strive for some GFM/Common Mark compatibility, although we have tables and IAL and I prefer not to overload markdown with features. However...

...we have created a plugin system for that kind of features. Would you be interested in writing one?

**Comment by walterbm** [comment]
@RobertDober sure, I would be glad to help create a plugin for Task Lists.

From looking through the current documentation it seems that plugins require the markdown lines to be prefixed with `$$`. Would it be possible to make a plugin for GFM tasks lists `- [ ]` with no prefix? If so, how could I integrate such a plugin into Earmark's current plugin system?

**Comment by RobertDober** [comment]
@walterbm Right now that is not possible, because of the simplicity of the plugin feature. I have no problem to make plugin backwards incompatible changes, and have already thought about better syntax. I could imagine the following syntax
```markdown
# TODO
$$> Walter's Great Plugin
- [ ] foo the bar
...
$$<
```
Now your plugin will get the lines between `$$>` and `$$<` passed in and you could e.g. preprocess the task list and then call Earmark.as_html yourself on it, and return it according to the plugin convention.

I am listening to alternative ideas with pleasure though, as long as we do not break non plugin using markdown.

**Comment by LostKobrakai** [comment]
It would be nice if the readme would at least mention that gfm is only partially supported. Currently I'd expect it to enable all the gfm extentions.

**Comment by RobertDober** [comment]
@LostKobrakai sorry you were misslead, I'll have a look at that. Gfm is a fast moving target so I guess we should definitely clarify.
