### ISSUE TITLE
bug in list item block detection, nested lists detection is incorrect

### ISSUE THREAD

**Issue by brainlid** [pragdave/earmark#127]
The following markdown incorrectly gets compiled to the following html.

The problem is that the first sub item is starting a new block but it ends up incorrectly grouping the blocks. So "level 3 - 2" ends up being a sibling of "level 2 - 1".

```markdown
- Level 1
  - level 2 - 1
    - level 3 - 1
    - level 3 - 2
    - level 3 - 3
  - level 2 - 2
```

```html
<ul>
    <li>
        <p>Level 1</p>
        <ul>
            <li>
                <p>level 2 - 1</p>
                <ul>
                    <li>level 3 - 1
                    </li>
                </ul>
            </li>
            <li>level 3 - 2
            </li>
            <li>level 3 - 3
            </li>
        </ul>
    </li>
    <li>level 2 - 2
    </li>
</ul>
```

Which ends up looking like this:

<ul>
    <li>
        <p>Level 1</p>
        <ul>
            <li>
                <p>level 2 - 1</p>
                <ul>
                    <li>level 3 - 1
                    </li>
                </ul>
            </li>
            <li>level 3 - 2
            </li>
            <li>level 3 - 3
            </li>
        </ul>
    </li>
    <li>level 2 - 2
    </li>
</ul>

**Comment by RobertDober** [comment]
Tank you for reporting this

**Comment by RobertDober** [comment]
Regression from 1.0

**Comment by RobertDober** [comment]
As this regression was as des by implmenting 2 Space indent one can workaround the bug with 4 space indent before I fix it

**Comment by brainlid** [comment]
Thanks for the workaround. That does work pretty well for me.
