### ISSUE TITLE
Incorrect rendering of numbered lists

### ISSUE THREAD

**Issue by alco** [pragdave/earmark#13]
Rendering [this list](https://gist.githubusercontent.com/alco/4207ba8d61e734a6c2a4/raw/5e77c222fed3a947cc1b3a0cfc91527823680b9a/gistfile1.txt) produces the following HTML output (tested on master):

```html
<h2>API</h2>
<p>This module provides 3 main APIs for you to use:</p>
<p>  1. Evaluate a string (<code class="inline">eval_string</code>) or a file (<code class="inline">eval_file</code>)</p>
<pre><code>directly. This is the simplest API to use but also the
 slowest, since the code is evaluated and not compiled before.</code></pre>
<p>  2. Define a function from a string (<code class="inline">function_from_string</code>)</p>
<pre><code>or a file (`function_from_file`). This allows you to embed
 the template as a function inside a module which will then
 be compiled. This is the preferred API if you have access
 to the template at compilation time.</code></pre>
<p>  3. Compile a string (<code class="inline">compile_string</code>) or a file (<code class="inline">compile_file</code>)</p>
<pre><code>into Elixir syntax tree. This is the API used by both functions
 above and is available to you if you want to provide your own
 ways of handling the compiled template.</code></pre>
```

I call this incorrect because the majority of Markdown implementations out there handle this list as expected. Try pasting the text above into [Babelmark](http://johnmacfarlane.net/babelmark2), you will see a single processor that has behaviour similar to earmark. All other markdown processors produce a proper list.

This issue has first been spotted on this page – http://elixir-lang.org/docs/stable/eex/EEx.html. Similar problem can be found on these pages:

  * http://elixir-lang.org/docs/stable/elixir/Kernel.SpecialForms.html#__aliases__/1
  * http://elixir-lang.org/docs/stable/elixir/Process.html#exit/2

The list style for Elixir doc strings was a deliberate choice ([this commit](https://github.com/elixir-lang/elixir/commit/41c74e96824b1a64379d936ebe486f9e3f371bc7)) to support multiple paragraphs of text mixed with source code blocks in a single list item. This choice was based on the results of the majority of markdown processors on Babelmark, not on the markdown "spec" itself.

Lastly, here's how GitHub renders the original list:

## API

This module provides 3 main APIs for you to use:

  1. Evaluate a string (`eval_string`) or a file (`eval_file`)
     directly. This is the simplest API to use but also the
     slowest, since the code is evaluated and not compiled before.

  2. Define a function from a string (`function_from_string`)
     or a file (`function_from_file`). This allows you to embed
     the template as a function inside a module which will then
     be compiled. This is the preferred API if you have access
     to the template at compilation time.

  3. Compile a string (`compile_string`) or a file (`compile_file`)
     into Elixir syntax tree. This is the API used by both functions
     above and is available to you if you want to provide your own
     ways of handling the compiled template.

**Comment by pragdave** [comment]
I understand the issue.

However, I dont understand why the source needs to be indented the way it
is.

The simplest and most compatible fix is to indent as

asdasddsa

1. asdads
    asdsadas

2. asdasdsad
    asdasdasd


Dave

**Comment by alco** [comment]
@pragdave

See this section http://daringfireball.net/projects/markdown/syntax#list.

> List markers typically start at the left margin, but may be indented by up to three spaces.

Indenting slightly helps lists to stand out from the ordinary paragraphs.

> To make lists look nice, you can wrap items with hanging indents
> [...]
> But if you want to be lazy, you don’t have to
> [...]

In Elixir, we want lists to be nice (we don't want to be lazy).

**Comment by pragdave** [comment]
I understand. But you can still use hanging indents, as long as the
indentation of the block is less than 4 characters.

I have some family issues at the moment, and I won't have time to make
changes. So as a short term measure, my suggestion is to simply bring the
indentation closer to the margin.

(Or, I'll take a PR :)


Dave
