### ISSUE TITLE
IAL for a tags doesn't work

### ISSUE THREAD

**Issue by exterm** [pragdave/earmark#131]
Hi, I just wanted to add a `target="blank"` to a link and noticed that it doesn't work.

According to Kramdown syntax, `[nice link](http://www.google.com){:target="blank"}` should work, but earmark just renders the curly braces and their content as plain text. When I but the curly braces on the next line, like
```
[nice link](http://www.google.com)
{:target="blank"}
```
The target attribute is added to the enclosing `p` tag instead.

**Comment by exterm** [comment]
Thank you for the brilliant open source library :+1:

**Comment by RobertDober** [comment]
Thank you for your kind words.
Concerning the issue I am afraid I have to close it.
It seems that Maruku, Kramdown and Earmark agree on this, the IAL atts go to the surrounding `p` tag https://johnmacfarlane.net/babelmark2/?text=%5Ba%5D(http%3A%2F%2Fw.com)%0A%7B%3A+.blank+%7D

Given that for once all three implementations agree I guess we better keep it that way.
IAL is great, and I really appreciated Dave added it, but should not operate on the underlying rendering as it is applied to the last block element (roughly speaking).

You can still write your link as HTML of course, I know it is a pain but it's the best I can offer, unless
one writes a plugin, should be easy, would you be interested? I'd gladly help you with this.

**Comment by exterm** [comment]
So there's no way of adding attributes to `a` tags?

See https://johnmacfarlane.net/babelmark2/?text=[a](http%3A%2F%2Fw.com){%3Atarget%3D"_blank"} for a version that works in Kramdown, but not in earmark. Although most implementations seem to disagree with Kramdown. But as you mention Kramdown in your documentation, I expected this to work in earmark too.

**Comment by RobertDober** [comment]
Hmm I really do not know. Would be nice to have but I will need some time to see if it is not too punishing and to consider some other cases.
But you have succeeded in convincing me that there might be a way, so I'll reopened it. But honestly I am not sure if and when...

**Comment by exterm** [comment]
That's OK, I have a very nasty `String.replace` workaround for that right now, it would just be nice to be able to remove that some time in the future :)
