### ISSUE TITLE
Footnotes: odd behaviour after an error.

### ISSUE THREAD

**Issue by jamiecurle** [pragdave/earmark#137]
Firstly, Earmark is super useful and a great resource so thanks for spending your time on it.

I forked this repo this morning to try and get to the bottom of a footnote issue (_a footnote with single word does not save_) and in doing so I have uncovered something that is perplexing me. 

Open up an console in the Earmark directory (_running off master_) with `iex -S mix` and you can use these steps to re-create.

Take a valid footnote (_almost verbatim from `test/acceptance/footnotes_test.exs`_) such as this:

```elixir
Earmark.as_html("foo[^1] again\n\n[^1]: bar baz", %Earmark.Options{footnotes: true})
```

This is the result:

```elixir
{:ok,
 "<p>foo<a href=\"#fn:1\" id=\"fnref:1\" class=\"footnote\" title=\"see footnote\">1</a> again</p>\n<div class=\"footnotes\">\n<hr>\n<ol>\n<li id=\"fn:1\"><p>bar baz&nbsp;<a href=\"#fnref:1\" title=\"return to article\" class=\"reversefootnote\">&#x21A9;</a></p>\n</li>\n</ol>\n\n</div>",
```

Which is expected.  So change it to a single word by hyphenating that space:

```elixir
Earmark.as_html("foo[^1] again\n\n[^1]: bar-baz", %Earmark.Options{footnotes: true})
```

And this is the error:

```elixir
{:error, "<p>foo<a href=\"bar-baz\" title=\"\">^1</a> again</p>\n",
 [{:error, 1, "footnote 1 undefined, reference to it ignored"}]}
```

This is the behaviour I was wanting to get to the bottom of (_single word as footnote content does not save_), but then then I discovered that if I change the single word back to the original, it does not succeed. It fails. It does so with the same error as the single hyphenated word, which is odd, because this new line of code is **exactly** the same line of code that worked in the first step.

```elixir
Earmark.as_html("foo[^1] again\n\n[^1]: bar baz", %Earmark.Options{footnotes: true})
{:error,
 "<p>foo<a href=\"#fn:1\" id=\"fnref:1\" class=\"footnote\" title=\"see footnote\">1</a> again</p>\n<div class=\"footnotes\">\n<hr>\n<ol>\n<li id=\"fn:1\"><p>bar baz&nbsp;<a href=\"#fnref:1\" title=\"return to article\" class=\"reversefootnote\">&#x21A9;</a></p>\n</li>\n</ol>\n\n</div>",
 [{:error, 1, "footnote 1 undefined, reference to it ignored"}]}
```

Before I started getting to the bottom of the single word thing, I wanted to know for certain if this is intended behaviour or a bug?  It will help me get my bearings. 

Thanks in advance humans.

**Comment by RobertDober** [comment]
Thank you for your feedback.

Let me answer your two questions.

First of all the `bar-baz`vs. `bar baz` issue. Working with Dave's code I assumed (I know, I know) that it was done on purpose, but looking at the following Babelmark output I am not sure anymore.

If you want to open an issue for it, I will look into it and ask Dave if this is ok with him.


Now the spoofy one, well it is quite simple I migrated error handling into an agent (adding some state, bad boy that I am) `Earmark.Global.Messages` which really helped to get the code much leaner by being able to issue an error in fire & forget manner without carrying it up in functional manner. 

The reasoning also being that a very unlike but potentially possible agent timeout would just imply a missing error message, not a big deal (I hope).

I never met the problem in iex, here is what you can do

```iex
iex(3)> Earmark.as_html("foo[^1] again\n\n[^1]: bar baz", %Earmark.Options{footnotes: true})
{:error,
 "<p>foo<a href=\"#fn:1\" id=\"fnref:1\" class=\"footnote\" title=\"see footnote\">1</a> again</p>\n<div class=\"footnotes\">\n<hr>\n<ol>\n<li id=\"fn:1\"><p>bar baz&nbsp;<a href=\"#fnref:1\" title=\"return to article\" class=\"reversefootnote\">&#x21A9;</a></p>\n</li>\n</ol>\n\n</div>",
 [{:error, 1, "footnote 1 undefined, reference to it ignored"}]
iex(4)> Agent.stop(Earmark.Global.Messages)
:ok
iex(5)> Earmark.as_html("foo[^1] again\n\n[^1]: bar baz", %Earmark.Options{footnotes: true})
{:ok,
 "<p>foo<a href=\"#fn:1\" id=\"fnref:1\" class=\"footnote\" title=\"see footnote\">1</a> again</p>\n<div class=\"footnotes\">\n<hr>\n<ol>\n<li id=\"fn:1\"><p>bar baz&nbsp;<a href=\"#fnref:1\" title=\"return to article\" class=\"reversefootnote\">&#x21A9;</a></p>\n</li>\n</ol>\n\n</div>",
 []}
iex(6)>

```

I guess we will add a more convenient `Earmark.Global.Messages.stop in the future.

**Comment by RobertDober** [comment]
And now with two words

foo[^1] again

[^1]: bar baz

**Comment by jamiecurle** [comment]
Thanks for the speedy and in depth reply,  that all makes sense.

I will open up an issue about the single word footnotes.

**Comment by RobertDober** [comment]
Actually it really does not cost anything to stop the Agent in `as_html` and `as_html!` so I keep this one open for that enhancement.

**Comment by RobertDober** [comment]
I have allowed plugins to call `Earmark.as_html` and can therefore not shut the message agent down.  Well that tougth me a lot again about state, I thought it was safe to introduce state, but troubles are lurking around every corner when you do so. For now I won't fix it therefore. :cry:
