### ISSUE TITLE
Support CommonMark-style hard line breaks?

### ISSUE THREAD

**Issue by notriddle** [pragdave/earmark#139]
In CommonMark, and the current version of GFM, a hard line break can be made without trailing white space, using a backslash escape:

    Roses are red\
    Violets are blue\
    Rhyming is hard\
    Let's add support for popular Markdown extensions

> Roses are red\
> Violets are blue\
> Rhyming is hard\
> Let's add support for popular Markdown extensions

<http://spec.commonmark.org/0.27/#example-291>

**Comment by RobertDober** [comment]
Good news I like it, and we should have it.

Bad news I am really lacking time right now.

Anyway thank you for reporting this.

**Comment by RobertDober** [comment]
@pragdave I have checked this with Babelmark and Github and it was easy to implement the exact behavior in #140 . I implemented this **only** for `gfm: true`. Do you agree with this feature?

**Comment by notriddle** [comment]
Sure, no problem there!

**Comment by RobertDober** [comment]
Actually I was asking @pragdave

**Comment by andreaazzini** [comment]
News about this feature?

**Comment by RobertDober** [comment]
I will ping Dave

**Comment by RobertDober** [comment]
Got the green light from Dave and merged.
