### ISSUE TITLE
add support for: links in headings

### ISSUE THREAD

**Issue by eksperimental** [pragdave/earmark#15]
Hi Dave,
I don't know if this is part of the markdown features, or something is missing,
but i think it will be usefull to allow links inside headers.

```
iex(4)> Earmark.to_html("## [Pygments](http://pygments.org/)")
"<h2>[Pygments](http://pygments.org/)</h2>\n"
```

Every implementation featured in babelmark2 is supporting this:
http://johnmacfarlane.net/babelmark2/?normalize=1&text=text%0A%0A%23%23+This+is+the+heading+%5BPygments%5D(http%3A%2F%2Fpygments.org%2F)%0A%0Amore+text%0A%0A%23%23+%5BPygments%5D(http%3A%2F%2Fpygments.org%2F)%0A

this is what it looks like in earmark:
![earmark_heading](https://cloud.githubusercontent.com/assets/9133420/6020298/c9b88340-abdc-11e4-87b2-5fc64cd00f97.png)

Cheers

**Comment by pragdave** [comment]
I thought hard about this when you posted the ticket. I've decided I don't really like the idea. To my mind, headings are for internal navigation, not external. They act as targets, not as links.

**Comment by eksperimental** [comment]
thanks anyway for considering it
