### ISSUE TITLE
Doesn't parse everything

### ISSUE THREAD

**Issue by GildedHonour** [pragdave/earmark#152]
Some tags are parsed correctly, some aren't:

![screenshot_2017-07-07_15-11-30](https://user-images.githubusercontent.com/2032888/27947070-fd6bb190-6326-11e7-88e1-6cbe4361f473.png)

I'm using it as    ` <%= raw(Earmark.to_html(@article.body)) %>`

**Comment by RobertDober** [comment]
Thanx for your report, however I do not see the input causing the trouble. Can you provide the markdown file and indicate the error in the HTLM.

Also which version of Earmark to you use? Seems it is outdated by the usage of `to_html`

**Comment by GildedHonour** [comment]
> Can you provide the markdown file and indicate the error in the HTLM.
what's the markdown file? where is that mentioned in the documentation?
there's no error in HTML as you can see.

I've updagrated it to 1.2 and am using as_html!, but there's no change.

**Comment by GildedHonour** [comment]
also

```
$ mix escript.build
** (Mix) Could not generate escript, please set :main_module in your project configuration (under :escript option) to a module that implements main/1
```

hasn't  setting the main module become obsolete in Elixir applications?

**Comment by RobertDober** [comment]
I have no clue what problem you are talking about?
What do you want to set up?
What do you want to change in the current behavior of what application?
In which context do you run your `mix escript.build`.

May I suggest to ask on the [Elixir Forum](https://elixirforum.com/), I am no expert on Phoenix or setting up Elixir applications.

I would also suggest to give a pointer to your application.

**Comment by GildedHonour** [comment]
why haven't "quote" and "header" been replaced with html?

**Comment by RobertDober** [comment]
Please refer yourself to the resources I gave to you.
