### ISSUE TITLE
Doesn't parse everything - 2

### ISSUE THREAD

**Issue by GildedHonour** [pragdave/earmark#153]
Some tags are parsed correctly, some aren't:

![screenshot_2017-07-07_15-11-30](https://user-images.githubusercontent.com/2032888/27947070-fd6bb190-6326-11e7-88e1-6cbe4361f473.png)

I'm using it as    ` <%= raw(Earmark.to_html(@article.body)) %>`

**Comment by pragdave** [comment]
This isn't Markdown input. To get the same effect in Markdown you'd use something like

~~~
*strong text*

> quote wdfewfewfwf

## header
~~~

Regards


Dave Thomas

**Comment by GildedHonour** [comment]
@pragdave that's what that is, it's just show with quotes in chrome debugger, in chrome->page->view source there're no quotes.

**Comment by pragdave** [comment]
@article.body doesn't appear to be valid markdown.  It seems to have HTML
in it.

**Comment by GildedHonour** [comment]
thanks.

**Comment by RobertDober** [comment]
Again my apologies for my terrible communication skills...

I just do not get it :(.


Take care

Robert

--
Non datemi consigli che so sbagliare da solo
(Giuseppe Di Stefano)
