### ISSUE TITLE
Unclosed backquotes issue for text `\`

### ISSUE THREAD

**Issue by semanticart** [pragdave/earmark#154]
I've pushed a failing test to [a branch](https://github.com/semanticart/earmark/commit/a5a92793e453987baedef24f7b43415509428138). That might be a poor choice of test in a poor choice of place but it will at least illustrate the issue.

I encountered this while parsing a blog post that wanted to draw special attention to the backslash character: `\`. With the simplified input

<pre>
`\`

```ruby
a = 1 + 2
b = a + 1
```
</pre>

The initial backslash causes the second backtick to be escaped which leaves the backticks unclosed.

So instead of expected output, you end up with subsequent content being treated as inline.

```html
<p><code class=\"inline\">\\</code>\n\n<code class=\"inline\">ruby\na = 1 + 2\nb = a + 1</code></p>\n
```

It works on github (tada: `\`) and seems to work as expected in the 1.0.1 version of the official markdown converter.

Thanks for the great library and please let me know if I can be of additional help.

**Comment by RobertDober** [comment]
Thank you for the report. Any additional help would be a PR, right now I have no idea if it is simple but I am afraid that rather not...

Worst, AFAIK, there is no workaround, meaning I did not find any input creating the output you desired, which is something like that, I guess:

```html
p><code>\</code>

</p>
<pre><code class="ruby">a = 1 + 2
b = a + 1</code></pre>
```

**Comment by semanticart** [comment]
Thanks for taking a look. 

I _can_ confirm that the output you show above is more-or-less what I expect for this simplified example.

I've been able to work around this problem on my end in the meantime by replacing the `\` with `<code class="inline">\</code>`

**Comment by RobertDober** [comment]
I am afraid we have to pass on CommonMark compliance here. Unless introducing backward incompatibilities - and quite a bit of work - we shall not remove the escaping function of `\` before `\`` (let's see how Github renders these ;)).

However we definitely need to render `\`\\\\\`` accordingly.

**Comment by RobertDober** [comment]
Actually I missed a level of escaping in IEx. There was no bug.

Please have a look to the regression test for details. https://github.com/pragdave/earmark/blob/master/test/regressions/i154_escape_single_backslash_insided_inline_code_test.exs
