### ISSUE TITLE
External code renderers

### ISSUE THREAD

**Issue by tmbb** [pragdave/earmark#155]
I have an external `render_code` function I want to hook to earmark. The problam is that earmark seems to assume that code will be served in plaintext and highlighted by javascript. My function highlights code with HTML and CSS. That y itself is not a problem. The problem is that you enforce these delimiters:

```html
<pre><code class="[something chosen by you depending on the language]">
....
</pre></code>
```

I want to have a common code class, independent of the language, say, `"highlight"`:

```html
<pre><code class="highlight">
....
</pre></code>
```

That's currently impossible because you render the outermost tag yourselves. I can wrap the inside of the code in a span tag, or a div with the class I want or something like that, but I think it's cleaner if you allow external renders to do whatever they want. They might not even want to render inside `<pre></pre>` (I might wan to render code in a non-monospaced font, or inside a table for better spacing, and that's awkward inside pre). As things are now, I can always enclose my code in a `<span></span>` tag with the class I want, but then I still have to deal with the classes you add to the `<code>` tag.

Is there any way for you to provide an alternative API to render code that does not impose these constraints?

I'm thinking of something like this:

* if the `render_code` function returns a string, it's rendered inside the `<pre></pre>` tag as it is done now.
* if the `render_code` returns a tagged tuple (for example `{:no_pre, string}`) you it would be rendered verbatim without the `<pre>` tag.

This doesn't break backward compatibility and allows for more flexible rendering.

**Comment by RobertDober** [comment]
Thanx for your report.


Right now, all you can do is this

    iex(3)> x="""
    ...(3)> ```
    ...(3)>    def a
    ...(3)> ```
    ...(3)> {:class=highlight}
    ...(3)> """
     "```\n   def a\n```\n{:class=highlight}\n"
     iex(4)> Earmark.as_html(x)
     {:ok, "<pre class=\"highlight\"><code class=\"\">   def a</code></pre>\n", []}

Not _exactly what you want but maybe you cannot.

However this seems to be a not so uncommon issue and you might be interested in issue #145 which should deliver exactly what you want, if I understood correctly. Please feel free to participate in the discussion on #145.

Ok for you if I close this issue, or did I miss something?

**Comment by tmbb** [comment]
Hm... #145 is something else entirely. You have (wisely) provided an extension point for earmark with the `render_code` function. I just think you've made a design mistake by making too many assumptionson how the code is meant to be rendered. You hardcode the pre tag and the classes. IMO it makes more sense to have that part generated by the `render_code` function. I can already produce exactly the visual output I want with earmark as it is: I just enclose the whole code in a span tag with the class I want. It's just enclosed in a a useless css class I have no control over :)

But if you think #145 is the way to go, I'll discuss there.

**Comment by RobertDober** [comment]
The useless tag, could it not be removed in #145? However I will keep this open unless #145 is implemented then we will see clearer.

I need to stay very superficial right now in my analysis, lack of time. :sob:
