### ISSUE TITLE
How to extend it, does it support extentions -- pre/post-process markdown on save/edit/show?

### ISSUE THREAD

**Issue by GildedHonour** [pragdave/earmark#156]
Say, I don't want to store a full url of an image in database because all the images will be with a common prefix such "https://example.com/images/articles". And thus I want to cut off that prefix when I'm adding/editing an article with an image and also dynamically add that prefix when I'm showing that article. In other words, I want to pre- and post-process markdown. It may not be only "img" but any markdown tag. Does earmark support this?

**Comment by RobertDober** [comment]
Short answer: No. Earmark is a Markdown converter, and AFAIK that is nothing Markdown is designed to do.

But asI completely understand the itch you want to scratch I want to give a long answer too :wink: 

 I believe that the general way to do this is by implementing post processors.

Again, AFAIK there is no standardized AST representation of a Markdown document and I am very excited about exposing one as we are discussing in #145 .

But please do us not let forget about the importance that Earmark has in the Elixir Ecosystem for generating docs. It will always be the highest priority to keep that stable and backwards compatible.

Exposing an AST is of course no technical threat to that goal but it is also not something you should not expect very soon, and even then for some time it might leave you quite some work for rendering  and unstable interfaces.

Also, as you were talking about _preprocessing_. Maybe using EEx on your markdown would do the preprocessing part?

Sorry that is about all I can say about this for the time being.
