### ISSUE TITLE
Is there a way to use an older version of :earmark? I'm not looking to possibly break my VM just to run it with ex_doc

### ISSUE THREAD

**Issue by mfergu** [pragdave/earmark#157]
/Documents/udemy/elixir/cards$ mix deps.update earmark
Running dependency resolution...
Dependency resolution completed:
  earmark 1.2.3
  ex_doc 0.16.2

/Documents/udemy/elixir/cards$ lsb_release -c 
Codename:	vivid

/Documents/udemy/elixir/cards$ mix docs==> earmark
warning: the dependency :earmark requires Elixir "~> 1.4" but you are running on v1.2.3
Compiled lib/earmark/helpers.ex
Compiled lib/earmark/error.ex

== Compilation error on file lib/earmark/helpers/leex_helpers.ex ==
** (CompileError) lib/earmark/helpers/leex_helpers.ex:17: undefined function to_charlist/1
    (stdlib) lists.erl:1337: :lists.foreach/2
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6

could not compile dependency :earmark, "mix compile" failed. You can recompile this dependency with "mix deps.compile earmark", update it with "mix deps.update earmark" or clean it with "mix deps.clean earmark"

/Documents/udemy/elixir/cards$ ./earmark --help
bash: ./earmark: No such file or directory

**Comment by RobertDober** [comment]
I guess that your Earmark version results from the ex_doc dependenc, if that is untrue please post your mix.exs.

If it is true try to downgrade ex_doc until you find a compatible Earmark version which should be 1.1.1.

You can also force Earmark to 1.1.1 in your mix.exs and see what happens.

It might be difficult to find support for such an old Elixir version, any particular reason you cannot update?
