### ISSUE TITLE
how to recognize pure link string?

### ISSUE THREAD

**Issue by shisongsong** [pragdave/earmark#158]
I found that link strings can not be recognized with Earmark.as_html!(), did I miss something?

The given content is:
\* http:\/\/stackoverflow.com/questions/32481035/how-to-provide-correct-hostname-in-gitlab-confirmation-email\r\n

I hope it shows this:
*  http://stackoverflow.com/questions/32481035/how-to-provide-correct-hostname-in-gitlab-confirmation-email

But it displays without link highlight, like this:
* http:\/\/stackoverflow.com/questions/32481035/how-to-provide-correct-hostname-in-gitlab-confirmation-email

**Comment by RobertDober** [comment]
Hmm I am not sure what input are you refering to? The source of the SO question you referenced above.
I suggest you paste the markdown which causes you trouble and tell us the html you would like to see generated for it.

**Comment by ericmj** [comment]
I think the problem is that pure links in markdown i.e. `http://exapmple.com/foo/bar` does not render as a `<a>` link. It's unclear to me if markdown supports this but github does in its markdown rendering.

**Comment by ericmj** [comment]
Given the markdown: `http://example.com/foo/bar`.

Should produce: `<a href="http://example.com/foo/bar">http://example.com/foo/bar</a>`.

If you want to support this feature.

**Comment by shisongsong** [comment]
@ericmj Yes, thank you very much, that's what I want, but when I use the `Earmark.as_html!`, it doesn't produce   `<a href="http://example.com/foo/bar">http://example.com/foo/bar</a>`, it will produce just `http://example.com/foo/bar` @RobertDober

**Comment by RobertDober** [comment]
Ah pure links, thank you @ericmj for getting me into the context. 

I am not against it, I guess it would be a valuable feature.

**Comment by shisongsong** [comment]
Okay, now you understand what I mean, thanks anyway, both of you are so nice people. @RobertDober @ericmj

**Comment by sn3p** [comment]
> a correct implementation will be braking current behavior
> 
> Therefore a first step would be to deprecate the current behavior where necessary and only change the behavior in 1.4.

Just curious, how does implementing the [autolink extension](https://github.github.com/gfm/#autolinks-extension-) break the current behaviour? The [standard autolink](https://github.github.com/gfm/#autolink) is still valid in GFM. So no need to deprecate, or am I missing something?

Btw I would love this feature in Earmark 😎

**Comment by RobertDober** [comment]
It simply changes the former behavior, maybe I am little bit paranoid (10+ years of sysadmin) but you can get an idea of how much work that is [here](https://github.com/pragdave/earmark/pull/231/files#diff-8b0ee31e0381f6629afe7e51ab301cc8) and I have only speced about 50% (IIRC) of the GFM examples during my X-mas break.

It also might be that some input we autolink now will not be autolinked under GFM so that is even more probable to generate problems.

Therefor this will take some time, sorry.

But by all means look at the deprecations I have added and if you think that I can do this quicker, I am all ears, but the goal is not to get issues opened after the next release, why is there a link in my ex_doc.

**Comment by RobertDober** [comment]
depends on #217

**Comment by mrifat** [comment]
@RobertDober this issues seems old and not yet implemented, are you dropping it or is there another way to handle this that does not require this update anymore?

**Comment by RobertDober** [comment]
I am overworked and trying to figure out what to prioritize, but definitely not dropping it.

I wanted to get a clear shot at this, and if you look at #217 the spec is quite large, maybe I could just get some autolinks working say whatever corresponds to

      ```%r{\bhttps?://\S+\b}```

❓

**Comment by mrifat** [comment]
Sorry for the late reply, overworked here as well.
Yeah that would work for most of the spec, it'd also give you extra time to support whatever breaks this pattern when users report them, which might not be soon 🤞 

Also thanks for doing this ❤️
