### ISSUE TITLE
Block level HTML containing newline messes up formatting

### ISSUE THREAD

**Issue by balexand** [pragdave/earmark#159]
This test reproduces the problem:

```elixir
# FAIL
assert Earmark.as_html!("<p class=\"intro\">a\nb</p>\n\nnext") ==
  "<p class=\"intro\">a\nb</p><p>next</p>\n"
```

```
Assertion with == failed
code:  assert Earmark.as_html!("<p class=\"intro\">a\nb</p>\n\nnext") == "<p class=\"intro\">a\nb</p><p>next</p>\n"
left:  "<p class=\"intro\">a\nb</p>\n\nnext"
right: "<p class=\"intro\">a\nb</p><p>next</p>\n"
```

This seems to happen with any block level element:

```elixir
# FAIL
assert Earmark.as_html!("<div>a\nb</div>\n\nnext") ==
  "<div>a\nb</div><p>next</p>\n"
```

```
Assertion with == failed
code:  assert Earmark.as_html!("<div>a\nb</div>\n\nnext") == "<div>a\nb</div><p>next</p>\n"
left:  "<div>a\nb</div>\n\nnext"
right: "<div>a\nb</div><p>next</p>\n"
```

As a workaround, the markdown can be formatted differently:

```elixir
# PASS
assert Earmark.as_html!("<p class=\"intro\">\na\nb\n</p>\n\nnext") ==
  "<p class=\"intro\">\na\nb\n</p><p>next</p>\n"

# PASS
assert Earmark.as_html!("<p class=\"intro\">ab</p>\n\nnext") ==
  "<p class=\"intro\">ab</p><p>next</p>\n"
```

I've compared this behavior to [Kramdown](https://kramdown.gettalong.org), [Redcarpet](https://github.com/vmg/redcarpet), and [Maruku](https://github.com/bhollis/maruku). Those libraries all render this markdown correctly.

**Comment by RobertDober** [comment]
@balexand Thank you for reporting this, hopefully finding some time soon ...

**Comment by RobertDober** [comment]
@balexand I just realised during writing the test cases that you _forgot_ to put the closing blocklevel tag on its own line.
I reckon that the doc only explains that for **nested block elements** but actually that is true for all blocklevel tags. I will update the docs accordingly.
