### ISSUE TITLE
add earmark to babelmark2

### ISSUE THREAD

**Issue by eksperimental** [pragdave/earmark#16]
A server needs to be set up with earmark, but I think it will be a good asset to have it in [Babelmark2](http://johnmacfarlane.net/babelmark2/)

info on how to add it: http://johnmacfarlane.net/babelmark2/faq.html#how-can-i-add-my-markdown-implementation-to-babelmark-2

**Comment by pragdave** [comment]
At the risk of channelling DHH, please feel free. I personally don't have the bandwidth to maintain another server.

Dave
