### ISSUE TITLE
Be clear in README which parts of GFM are supported.

### ISSUE THREAD

**Issue by RobertDober** [pragdave/earmark#161]
as mentioned in  https://github.com/pragdave/earmark/issues/126#issuecomment-335722014 users might expect a more complete implementation of GFM features.

GFM will probably evolve so mentioning the exact features implemented is a good idea.

**Comment by Crissov** [comment]
As mentioned in #176, this effectively means also documenting the differences from Commonmark because GFM now builds upon that.

**Comment by pragdave** [comment]
This looks good to me.

A thought: if the moduledoc for earmark.ex is just the README, we could replace it with

~~~ elixir
@moduledoc File.read!("../README.md")
~~~

so there'd only be one place to change it.

DRY, you know... :)

**Comment by RobertDober** [comment]
It is supposed to work the other way, README.md contains docstrings so to reflect the hexdocs.

**Comment by pragdave** [comment]
But the readme has to be static. The hexdocs are dynamic

**Comment by RobertDober** [comment]
I am confused Dave.

The mix task readme imports selected docstrings into the README.md. I always was under the impression that your goal was to have a README that will be synchronized with the docs at hex.pm.

I took this even as an inspiration to write this https://github.com/RobertDober/read_doc :blush:

Surely we could read the README.md into the moduledoc of  earmark.ex, why not we could lose the mix task...

However we also would lose the flexibility of today's solution, meaning we cannot compose the README from many docstrings.

Right now we _import_  `Earmark` and `Earmark.Plugin` 's moduledoc and `Earmark.as_html`'s functiondoc.

**Comment by pragdave** [comment]
You are right, of course. I'd forgotten about the mix task.

I really am sorry to have wasted your time.

**Comment by RobertDober** [comment]
No need to be.

--
Non datemi consigli che so sbagliare da solo
(Giuseppe Di Stefano)
