### ISSUE TITLE
set class attributes on paragraf tag.?

### ISSUE THREAD

**Issue by Schultzer** [pragdave/earmark#173]
Is there any convenient way to prefix all paragraph tag  class attributes

## Example 
```elixir
 iex> "[Google!](https://www.google.com)" |> Earmak.as_html!(class: "my_awesome_class")
"<p class=\"my_awesome_class\"><a href=\"https://www.google.com\">Google!</a>"
```

**Comment by RobertDober** [comment]
No, there is not, and this is not part of any Markdown extension I am aware of.

I cannot imagine that Earmark will support that kind of _postprocessing_.

Talking about _postprocessing_, this idea #145 might be of interest for you.
