### ISSUE TITLE
Commonmark conformance

### ISSUE THREAD

**Issue by Crissov** [pragdave/earmark#176]
The README claims only support for Gruber’s original Markdown and documents extensions and implementation choices from the, but GFM compatibility is clearly intended as well. Since GitHub switched to a [Commonmark compliant parser](https://GitHub.com/commonmark/cmark) in 2017, could you please document how Earmark differs from the CM spec (even if it is still not quite at v1.0 yet)?

**Comment by RobertDober** [comment]
absolutely, please see #161 

Allow me to close this as it is a doubleton I believe.

**Comment by Crissov** [comment]
Sure, I only searched for _commonmark_, which is not mentioned in that issue, but I agree that it is a duplicate. Thanks.

**Comment by RobertDober** [comment]
No problem feel free to add your thoughts/wishes to #161
