### ISSUE TITLE
README generation task `readme` is broken. **No Impact On Releases**

### ISSUE THREAD

**Issue by RobertDober** [pragdave/earmark#185]
Seems the info about the `moduledoc` inside README created another moduledoc 

I'll try to fix and enhance the `readme` task, this has no impact on the release.

**Comment by pragdave** [comment]
I've (finally) got hex.pm access. When I release, I get

~~~
Publishing package to public repository hexpm.
Proceed? [Yn]
Building docs...
** (EXIT from #PID<0.67.0>) an exception was raised:
    ** (ArgumentError) argument error
        (ex_doc) lib/ex_doc/formatter/html/autolink.ex:244: anonymous fn/7
in ExDoc.Formatter.HTML.Autolink.format_and_extract_typespec_placeholders/4
        (elixir) lib/macro.ex:258: Macro.do_traverse/4
        (elixir) lib/enum.ex:1402:
Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/macro.ex:244: Macro.do_traverse/4
        (elixir) lib/enum.ex:1402:
Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/enum.ex:1402:
Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/macro.ex:244: Macro.do_traverse/4
        (elixir) lib/enum.ex:1402:
Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
~~~

Any ideas?

**Comment by RobertDober** [comment]
Hi Dave

just come back from the weekend, I'll have a look at this A.S.A.P.

I do not think this is related to this bug which _just_ corrupts the README, but we will see.

**Comment by RobertDober** [comment]
Strange I could not reproduce the error with `mix hex.build` (Elixir 1.6.4/ OTP 20.3)

Here is the built .tar, in case it is of any help for you

[earmark-1.2.5.tar.zip](https://github.com/pragdave/earmark/files/1847085/earmark-1.2.5.tar.zip)

**Comment by RobertDober** [comment]
@pragdave anything else I can do?

**Comment by pragdave** [comment]
hex.build doesn't produce the docs.

The problem is in a typespec somewhere, but the error is not particularly
helpful.

**Comment by RobertDober** [comment]
oh sorry I see, now I need to get rid of asdf to be able to reproduce the error (as asdf does not put the escipts into `$HOME/.mix` this will take some time, but I am on it...

**Comment by RobertDober** [comment]
@pragdave seems I got down to it.

The kind folks of ex_doc are already working on the bugfix and I have identified ex_doc version `0.18.1` to be working

May I suggest the following procedure

* clone ex_doc
* `git checkout v0.18.3`
* `mix escript.build`
And now inside Elixir with a small modification that I pushed to master (needed for ASDF)
* `EX_DOC_ESCRIPT=full-path-to-buit-ex-doc mix hex.publish`
should work

The original procedure still works of course if you can install the ex_doc escript of v0.18.1, I failed :(

**Comment by RobertDober** [comment]
@pragdave ex_doc fixed in master no need to do anything special anymore
