### ISSUE TITLE
hexdocs not found

### ISSUE THREAD

**Issue by ConnorRigby** [pragdave/earmark#187]
https://hexdocs.pm/earmark/1.2.5/Earmark.html Points to a 404.

**Comment by RobertDober** [comment]
Thank you for the report and sorry for the late reply. Offline Vacations !!!

@pragdave I admit I did not check the docs link after the last release, is this an error from our side?

**Comment by pragdave** [comment]
I don't remember any error when we released it.

Should we push a point release?

**Comment by ericmj** [comment]
You can try building the docs locally with `mix docs`, you can also reupload only docs without cutting a new release by running `mix hex.publish docs`,

**Comment by RobertDober** [comment]
@pragdave I got it working again locally by updating my env (skipped to 1.6.5 and installed ex_doc as an escript from master)

```
EX_DOC_ESCRIPT=$HOME/.asdf/installs/elixir/1.6.5/.mix/escripts/ex_doc mix hex.publish docs                                                                       [15:46:52]
Local password:
[#########################] 100%
Publishing docs failed
account not authorized for this action
```

Can you please adapt this to your env and push the hex docs?

Thanks

I also guess our procedure is somehow hazardous, can we count on `ex_doc`
master to work correctly, probably I should have taken the commit with the version tag of the latest released version, lazy me.

**Comment by RobertDober** [comment]
@pragdave sorry for pushing, but it is my understanding that this 404 is a little bit disturbing. Is there anything else I can do by myself
