### ISSUE TITLE
Passing context to inline renderers

### ISSUE THREAD

**Issue by claytongentry** [pragdave/earmark#188]
Hi guys,

Love earmark!

I have a use case where having access to context in the inline renderer functions makes my life much easier. In this case, I'm using context to pass my own additional options into the renderer.

```
opts = %{foo: "bar"} |> Map.merge(%Earmark.Options{renderer: MyApp.HtmlRenderer})
Earmark.as_html!(md, opts)
```

Then in my ~link/3~ link/4 function, I'm essentially doing
```
def link(url, text, title, %Earmark.Context{options: options}) do
  if options[:foo] == "bar" do
    # this 
  else 
    # that
  end
end
```

Wondering how this strikes you, and if others would find this useful. I've gone ahead and branched my fork to implement this for `link`, which resolves my very particular use case: https://github.com/pragdave/earmark/compare/master...claytongentry:claytongentry/pass-context-to-link 

I'm happy to take a stab at extending it to the other functions if you agree with the approach. Otherwise, very appreciative of your guidance. Thanks!

**Comment by RobertDober** [comment]
I am afraid, it is who needs guidance. ;)

If I understand correctly your PR makes *only* sense if you plug a different `HtlmRenderer` into `%Earmark.Options{}` correct?

So we would assume a new contract for `HtmlRenderer` so to allow to plug a different one, and that implicitly and without doc.

But if I interpret your message correctly you would like to pass context into all public renderer functions, I guess we should create a protocol for `HtmlRender` anyway?

I would like to consider #145 in this context too!

What do you think?

**Comment by claytongentry** [comment]
@RobertDober I very much like the direction of the discussion in #145, and on further consideration I think transforming an AST is a more elegant solution than abusing context or the inline renderer APIs.

Will close this in favor of the changes proposed in #145.

Thanks!
