### ISSUE TITLE
Don't include generated src/*.erl in the package()

### ISSUE THREAD

**Issue by kipcole9** [pragdave/earmark#190]
`leex` and `yecc` generate files that have a reference to an Erlang version specific `.hrl` file.  Therefore when moving to Erlang/OTP 21 there is an Erlang compiler warning in `earmark` since the included `.erl` was generated on an earlier version.

If the *.erl files are not included in the `package()` definition in `mix.exs` then they will be generated on the current Erlang version without error.

I can send a PR if helpful, its a small change to `mix.exs` is all.

**Comment by RobertDober** [comment]
I'd appreciate a PR, help's always welcome, thank you for the report in any case.
