### ISSUE TITLE
IAL do not support inline code 

### ISSUE THREAD

**Issue by LostKobrakai** [pragdave/earmark#194]
Seems like earmark does not support the following, while it does support IAL for links.
```
`def index(conn, _params), do: […]`{:.language-elixir}
```

v 1.2.5

**Comment by RobertDober** [comment]
I merged your PR and therfore close this.

Vielen Dank für den Bugfix.

**Comment by RobertDober** [comment]
@LostKobrakai fyi although you are correct that the following renders illegal HTML...

```iex(37)> Earmark.as_html! ~s[<span class="ελληνικά">{:.greek   }τι κανις</span>] 
"<p><span class=\"ελληνικά\" class=\"greek\">τι κανις</span></p>\n"
```
it is under the user's control.

In this version of Earmark we do not (yet I hope) lexically analyse input like raw html and we would need to reparse yet again to sanitize the html.

You took care of two import cases
1. The inline class we add to inline code blocks and a potential _IALled_ class
1. multiple occurances of attributes inside an IAL.

Well done, thanx again.
