### ISSUE TITLE
Links with escaped chars are suffixed with end of url

### ISSUE THREAD

**Issue by hrynek** [pragdave/earmark#198]
```
[asdf1 \`qwer1\` zxcv1](http://ivalid.tld)
```
is rendered as
```html
<p><a href="http://ivalid.tld">asdf1 <code class="inline">qwer1</code> zxcv1</a>d)</p>
```

I would expect no `d)` after link. Number of appended chars is equal to number of escaped chars.

**Comment by hrynek** [comment]
And, of course, \<code\> should not be rendered at all :-)

**Comment by RobertDober** [comment]
@hrynek thank you for the bug report, yes it seems that we have two problems here.

**Comment by RobertDober** [comment]
should make it into 1.2.6 after all :grinning:

**Comment by hrynek** [comment]
Thanks for fast fix, but unfortunately escaped square brackets still cause same problem:
```
[asdf1 \[qwer1\] zxcv1](http://ivalid.tld)
```

**Comment by RobertDober** [comment]
hmm why did I treat them as exceptions? I'll check it out and let you know.

**Comment by RobertDober** [comment]
@hrynek just merged the _refix_

**Comment by hrynek** [comment]
Everything is OK now. Thank you.

**Comment by pragdave** [comment]
Robert:

I'm here. Can you do the release?

**Comment by RobertDober** [comment]
@pragdave with pleasure

**Comment by RobertDober** [comment]
Published
