### ISSUE TITLE
Pipe characters `|` in a table break outputted HTML

### ISSUE THREAD

**Issue by thecodeboss** [pragdave/earmark#206]
## Description

When placing `|` characters in a markdown table, inside a code block, it should render a table correctly. However, the `|` characters get interpreted as table separators, breaking the output.

I am aware I could use `\|` to insert pipe characters, however I want them to be inside backticks, and if I attempt to escape it like `` `\|\|` ``, it will render incorrectly.

## To reproduce

Run the following code:
```
s = """
| Operator | Description   | Example      | Result |
| -------- | ------------- | ------------ | ------ |
| `||`     | concatenation | `"a" || "b"` | `"ab"` |
"""

s |> Earmark.as_html! |> IO.puts
```

## Expected Output

```html
<table>
<colgroup>
<col>
<col>
<col>
<col>
</colgroup>
<thead>
<tr>
<th style="text-align: left">Operator</th><th style="text-align: left">Description</th><th style="text-align: left">Example</th><th style="text-align: left">Result</th>
</tr>
</thead>
<tr>
<td style="text-align: left"><code class="inline">||</code></td><td style="text-align: left">concatenation</td><td style="text-align: left"><code class="inline">&quot;a&quot; || &quot;b&quot;</code></td><td style="text-align: left"><code class="inline">&quot;ab&quot;</code></td>
</tr>
</table>
```

## Actual Output

```html
<table>
<colgroup>
<col>
<col>
<col>
<col>
</colgroup>
<thead>
<tr>
<th style="text-align: left">Operator</th><th style="text-align: left">Description</th><th style="text-align: left">Example</th><th style="text-align: left">Result</th>
</tr>
</thead>
</table>
<p>| <code class="inline">||</code>     | concatenation | <code class="inline">&quot;a&quot; || &quot;b&quot;</code> | <code class="inline">&quot;ab&quot;</code> |</p>
```

**Comment by RobertDober** [comment]
Thank you for reporting this.

**Comment by RobertDober** [comment]
@pragdave this is a tricky one.
In theory we should implement this feature only if `gfm: false` (or is it a bug in GFM?)
and only if we want this kind of commonmark compliance.

Personally I like it, but I would prefer to implement it for the default behavior too. `ex_doc` will certainly not set `gfm: false` so the usefullness would be limited.

Furthermore it is not a oneline fix either :cry:

Here are some references:

https://gist.github.com/RobertDober/d330c7b48294156102edd0a9de7171f1
 

https://babelmark.github.io
/?text=%7C+Operator+%7C+Description+++%7C+Example++++++%7C+Result+%7C%0A%7C+--------+%7C+-------------+%7C+------------+%7C+------+%7C%0A%7C+%60%7C%7C%60+++++%7C+concatenation+%7C+%60%22a%22+%7C%7C+%22b%22%60+%7C+%60%22ab%22%60+%7C1

**Comment by thecodeboss** [comment]
I did some investigation in GFM, and found this not a bug. They have [this example in the spec](https://github.github.com/gfm/#example-193):
> Include a pipe in a cell’s content by escaping it, including inside other inline spans:
> ```
> | f\|oo  |
> | ------ |
> | b `\|` az |
> | b **\|** im |
> ```
The behaviour when using `\|` seems to vary a lot though (see [Babelmark 3](https://babelmark.github.io/?text=%7C+Operator+%7C+Description+++%7C+Example++++++++%7C+Result+%7C%0A%7C+--------+%7C+-------------+%7C+--------------+%7C+------+%7C%0A%7C+%60%5C%7C%5C%7C%60+++%7C+concatenation+%7C+%60%22a%22+%5C%7C%5C%7C+%22b%22%60+%7C+%60%22ab%22%60+%7C)).

I think this issue can be closed. I tested using `\|` in Earmark and it seems to perform as expected:
```elixir
s = """
| Test  |
| ----- |
| `\\|` |
"""

s |> Earmark.as_html! |> IO.puts
```
outputs the following:
```html
<table>
<colgroup>
<col>
</colgroup>
<thead>
<tr>
<th style="text-align: left">Test</th>
</tr>
</thead>
<tr>
<td style="text-align: left"><code class="inline">|</code></td>
</tr>
</table>
```
Thanks for taking the time to look into it @RobertDober
