### ISSUE TITLE
Is it possible to configure automatic smart quotes separately from automatic em dash and en dash?

### ISSUE THREAD

**Issue by axelson** [pragdave/earmark#210]
Currently the `smartypants` option controls curly quotes, en dash, and em dash. I would like to be able to disable only curly quotes while keeping en dash and em dash support. I think the best way to support that would be to split `smartypants` into three separate configuration options. Is that something that would be accepted as a PR?

related: https://github.com/elixir-lang/ex_doc/issues/928, https://github.com/phoenixframework/phoenix/pull/3191

**Comment by RobertDober** [comment]
Hmm I do not know, I have two small issues with this:

- options creep

- and is the behavior even _wrong_ ? https://babelmark.github.io/?text=for+example+%22room%3A*%22%2C+%22users%3A*%22%2C+%22system%22
 
   - maruku does what we do
   - pandoc does an interesting thing
   - blackfriday, kramdown and s9e get it _right_

_ Will be edited vvvvv _

for example "room:*", "users:*", "system"

**Comment by axelson** [comment]
I'm not sure about any precedents for something like this and I can understand the concern about options creep. For a project that is rendering information about programming I'm always against introducing smart quotes since it is rarely what is wanted and often breaks code snippets (or makes it more difficult to use as a documentation system since you need to know how to avoid smart quotes, or that you do need to use backticks). Of course this is just my opinion and I realize that earmark is used for more than code documentation rendering via ex_doc.

> and is the behavior even wrong?

Not really, which is why I raised this issue to focus on providing an option to remove just the auto-smart quotes. There's obviously a problem with the input (which I why I also filed a PR on the phoenix docs)

> And yet another question @axelson would the input ~s{for example "room:"*, "users:*", "system"} not make more semantic sense?

No it doesn't make sense to change `"room:*"` to `"room:"*` because that changes the meaning of the Phoenix topic pattern. The correct input (IMHO) is 

    ~s{for example `"room:*"`, `"users:*"`, `"system"`}

Which has an unambiguous result on babelmark (and is what I implemented in the Phoenix PR): https://babelmark.github.io/?text=for+example+%60%22room%3A*%22%60%2C+%60%22users%3A*%22%60%2C+%60%22system%22%60

```
<p>
  for example <code>"room:*"</code>, <code>"users:*"</code>, <code>"system"</code>
</p>
```

**Comment by RobertDober** [comment]
I agree with what you say.

I really cannot grasp what the emphasis around quotes shall express, so I will not insist, just thought I had maybe figured it out LOL :blush: 

If @pragdave  agrees I will implement just one option, that should not be too bad, say `edashes` **better name very welcome**  and then `ex_doc` should use `smartypants: false, edashes: true` if they want.

That would be backward compatible too.

**Comment by pragdave** [comment]
Isn't smartypants disabled inside code fragments?

**Comment by axelson** [comment]
> Isn't smartypants disabled inside code fragments?

Yes, I believe that it is. In the original version of the phoenix doc code there was no code block (although there should have been)

**Comment by pragdave** [comment]
I don't think this is an issue, as long as we don't do the conversion to
curly quotes in between backticks.

**Comment by RobertDober** [comment]
we do not and I agree.
