### ISSUE TITLE
error diagnostics need love

### ISSUE THREAD

**Issue by RichMorin** [pragdave/earmark#211]
While parsing a Markdown document, I got this result:

    [:error, <input text>,
      {:warning, 78, "Closing unclosed backquotes ` at end of input"}
    ]

I'm not sure what the value 78 refers to, but in any event, having the line number for the opening backquote would have been useful in diagnosing the problem. Indeed, all such warnings should contain this sort of location information.

**Comment by RobertDober** [comment]
78 is the line number you are looking for,

e.g.

``` 
iex(22)> md = """                                                  
...(22)> hello 
...(22)> world `
...(22)> my friend
...(22)> """
"hello \nworld `\nmy friend\n"
iex(23)> Earmark.as_html md
{:error, "<p>hello \nworld `\nmy friend</p>\n",
 [{:warning, 2, "Closing unclosed backquotes ` at end of input"}]}
``` 

I'll check if the documentation concerning error messages can be improved.

**N.B.**

By running `as_html!` the error message is _human readable_ 

```
iex(24)> Earmark.as_html! md
<no file>:2: warning: Closing unclosed backquotes ` at end of input
"<p>hello \nworld `\nmy friend</p>\n"
```
