### ISSUE TITLE
Double space at the end won't translate to <br />

### ISSUE THREAD

**Issue by lobo-tuerto** [pragdave/earmark#212]
In the **README** it's mentioned that **Earmark** supports [Standard Gruber markdown.](https://daringfireball.net/projects/markdown/syntax)

And it's mentioned [there](https://daringfireball.net/projects/markdown/syntax#p) that:

> When you do want to insert a `<br />` break tag using Markdown, you end a line with two or more spaces, then type return.

So, I'm trying this:
(Notice the two spaces at the end of the first line)

```markdown
This is some **strong** text.  
This is some _emphasized_ text.
```

So, doing this:

```elixir
markdown = "This is some **strong** text.  \nThis is some _emphasized_ text."
html = Earmark.as_html!(markdown)
IO.inspect(html)
# => "<p>This is some <strong>strong</strong> text.  \nThis is some <em>emphasized</em> text.</p>\n"
```

Am I missing some option so it translates two ---or more--- consecutive spaces to a `<br />`?
(Not looking to translate every line-break into a `<br />`)

**Comment by RobertDober** [comment]
No you are not missing anything, this is indeed a bug, thank you for reporting it.

**Comment by lobo-tuerto** [comment]
@RobertDober Sorry to ask about this, but when are you going to push a new release that incorporates this fix?

**Comment by RobertDober** [comment]
I was planning to add #158 and maybe #171 to 1.3.1 before releasing. Now I can definitely push #171 to 1.3.2 if it shall take long. I'd say ETA of the release, maybe mid January.

But if this is urgent for you I guess I can release 1.3.1 in its current state. Ok for you @pragdave ?

**Comment by pragdave** [comment]
Absolutely.

**Comment by lobo-tuerto** [comment]
Thanks @RobertDober!

**Comment by RobertDober** [comment]
published
