### ISSUE TITLE
Open external links in a new tab

### ISSUE THREAD

**Issue by lex111** [pragdave/earmark#215]
Hello @RobertDober,

How can I do that?

**Comment by pragdave** [comment]
Alt click?

**Comment by lex111** [comment]
I meant how to make links automatically put a `target` attribute with the value `_blank`.

**Comment by pragdave** [comment]
I think that's frowned upon.... :)

**Comment by RobertDober** [comment]
Definitely not something we shall implement, however @lex111 you can put the link as html into a single line to achieve this.

**Comment by lex111** [comment]
And how can this be automated? Using plugins?

**Comment by pragdave** [comment]
I think what we're saying is that it is considered to be impolite for the creator of a page to open links in new tabs: if the reader wants that behavior they can simply right click out whatever. 

We won't be supporting this in Earmark

**Comment by RobertDober** [comment]
I meant that for any reason, e.g. because you are the user of the output or your customer wants that behavior, you can write your markdown differently

Instead of 

```md
     [Earmark](https://github/pragdave/earmark)
``` 

you write

```md
   <a href="..." target="_blank">Earmark</a>
``` 

Of course if you transform already existing markdown, sorry :blush:

**Comment by lex111** [comment]
Fine, thanks.

**Comment by davidkuhta** [comment]
For anyone looking for a regex:
`Regex.replace(~r/(\[.*\]\(.*\/\/.*\))/, "[Earm](https://github.com/pd/em)", "\\0{:target=_blank}")`
