### ISSUE TITLE
Trailing spaces can cause Earmark to emit spurious "br" tags.

### ISSUE THREAD

**Issue by RichMorin** [pragdave/earmark#222]
If paragraph input text contains two or more trailing spaces on an interior line, Earmark will emit a spurious `br` tag:

    iex(1)> "L1\nL2\n" |> Earmark.as_html()
    {:ok, "<p>L1\nL2</p>\n", []} 

    iex(2)> "L1 \nL2\n" |> Earmark.as_html()
    {:ok, "<p>L1 \nL2</p>\n", []}

    iex(3)> "L1  \nL2\n" |> Earmark.as_html()
    {:ok, "<p>L1<br>L2</p>\n", []}

    iex(4)> "L1   \nL2\n" |> Earmark.as_html()
    {:ok, "<p>L1<br>L2</p>\n", []}

Trailing spaces on the last line do not trigger this problem:

    iex(5)> "L1\nL2  \n" |> Earmark.as_html() 
    {:ok, "<p>L1\nL2  </p>\n", []}

The problem also affects quoted paragraphs:

    iex(6)> "> L1  \nL2\n" |> Earmark.as_html()  
    {:ok, "<blockquote><p>L1<br>L2</p>\n</blockquote>\n", []}

**Comment by pragdave** [comment]
that’s correct.

**Comment by pragdave** [comment]
sorry, I meant to add

https://daringfireball.net/projects/markdown/syntax#p

**Comment by RichMorin** [comment]
Yow!  I had no idea that was a Markdown "feature".  So, Earmark is simply acting
according to Gruber's design.  Learn something new every day...

Whether that's a _good_ part of the design is, of course, arguable.  Languages
that change their behavior based on invisible syntax differences are (IMNSHO)
setting the programmer up for failure, eg:

- the required use of leading tabs in make(1)
  (using spaces instead is probably the most common newbie error)

- the ability to mix leading spaces and tabs in Python

- the use of a backslash _just before_ the end of a line for continuation
  (any spaces after the backslash will cause mysterious syntax errors)

Owell, sorry for the spurious bug report...

-r

**Comment by RobertDober** [comment]
No problem at all @RichMorin let me just add that there are many things in  Markdown which are all but __good__ (just substitiute the "d" by an "f", simple typo making lots of sense).

BTW you forgot "git warning about files with trailing whitespace".


I believe you had a look at the link acceptance tests, you might have seen some strange things there :cry: 

Can I close the issue?

**Comment by RichMorin** [comment]
> On Mar 12, 2019, at 9:32 AM, Robert Dober <notifications@github.com> wrote:
> 
> Can I close the issue?

Yes (sigh).

-r

**Comment by RobertDober** [comment]
c'on it's not our fault 😉 
Thank you
