### ISSUE TITLE
Handling of link title syntax gets confused

### ISSUE THREAD

**Issue by RichMorin** [pragdave/earmark#224]
I have discovered a situation where Earmark's handling of link title syntax gets confused. I've boiled it down to two very similar input strings. One succeeds; the other fails:

    iex(1)> s = "The [Foo](/dash 'foo') page in \"bar\"\n" 
    "The [Foo](/dash 'foo') page in \"bar\"\n"
    iex(2)> Earmark.as_html(s)                            
    {:ok, "<p>The <a href=\"/dash\" title=\"foo\">Foo</a> page in “bar”</p>\n", []}

    iex(3)> s = "The [Foo](/dash 'foo') page (in \"bar\")\n"
    "The [Foo](/dash 'foo') page (in \"bar\")\n"
    iex(4)> Earmark.as_html(s)                              
    {:ok, "<p>The <a href=\"/dash\" title=\"bar\">Foo</a> page (in “bar”)</p>\n", []}

In boiling down the example, I ran across assorted peculiar behavior, so fixing the failing case above may or may not resolve all the problems. However, it seems like a good place to start.

**Comment by RobertDober** [comment]
Which case is failing? I feel the output is correct.

See also

https://babelmark.github.io/?text=The+%5BFoo%5D(%2Fdash+%27foo%27)+page+(in+%5C%22bar%5C%22)

**Comment by RichMorin** [comment]
Sorry; I thought about pointing out the difference, but didn't get around to doing so.  In the first case, the requested title (foo) is present in the HTML title attribute.  In the second case, "bar" shows up as the title. The only difference in the input Markdown is the presence of parentheses around "<<in “bar”>>.

**Comment by RobertDober** [comment]
I apologize, as I am on leave I did not look at it as well as I should have.

I will take care of it as soon as I have time to do it correctly.

Thank you for your understanding.

**Comment by RichMorin** [comment]
No problem; enjoy your leave!

**Comment by RichMorin** [comment]
I edited my mix.exs file as follows and the problem seems to have gone away:

      { :earmark, override: true,
          git: "https://github.com/pragdave/earmark.git" },

**Comment by RobertDober** [comment]
@RichMorin I just released https://hex.pm/packages/earmark/1.3.2
