### ISSUE TITLE
Git repo in earmark distribution?

### ISSUE THREAD

**Issue by RichMorin** [pragdave/earmark#227]
I recently set up a new Git repo for a project and got the following warnings:

    $ git init
    Initialized empty Git repository in .../from_spot/PA_all/.git/
    $ git add .
    warning: adding embedded git repository: PA_elixir/phx_http/deps/earmark
    hint: You've added another git repository inside your current repository.
    hint: Clones of the outer repository will not contain the contents of
    hint: the embedded repository and will not know how to obtain it.
    hint: If you meant to add a submodule, use:
    hint: 
    hint: 	git submodule add <url> PA_elixir/phx_http/deps/earmark
    hint: 
    hint: If you added this path by mistake, you can remove it from the
    hint: index with:
    hint: 
    hint: 	git rm --cached PA_elixir/phx_http/deps/earmark
    hint: 
    hint: See "git help submodule" for more information.

**Comment by RobertDober** [comment]
A quick check reveals nothing, I cannot really see where your submodule comes from.

I just installed Earmark in a mix project and everything is ok.

Any artefacts?

**Comment by RobertDober** [comment]
@RichMorin I would like to close this, any objections?

**Comment by RichMorin** [comment]
Feel free to close it; I assume it's a local issue.

-r

**Comment by RobertDober** [comment]
I guess so, as I did not succeed in reproducing it, reopen if you can reproduce in a new project please.
