### ISSUE TITLE
Markdown Metadata

### ISSUE THREAD

**Issue by surprisetalk** [pragdave/earmark#234]
Thank you so much for making Earmark!

I'm looking to parse a metadata header (something like [this](https://stackoverflow.com/questions/44215896/markdown-metadata-format)).

It would be amazing to have something like:
```elixir
{:ok, html, metadata} = Earmark.as_html_with_metadata!(markdown)
```

Have any thougts? I'm willing to make a PR if you think this would benefit other Earmark users.

**Comment by RobertDober** [comment]
Interesting, but I do not really see why the Markdown parser should do this, you can easily parse the header for yourself and then the rest with `Earmark`.

Are any other common markdown implementations implementing this?

**Comment by surprisetalk** [comment]
Most markdown parsers that support metadata (usually called "frontmatter") use a YAML header like this:

```
---
title: My Document
summary: A brief description of my document.
authors:
    - Waylan Limberg
    - Tom Christie
date: 2018-07-10
some_url: https://example.com
---
This is the first paragraph of the document.
```

- [Multimarkdown](http://fletcher.github.io/MultiMarkdown-5/metadata.html)'s parser omits the `---` and has a slightly tweaked version of YAML
- [Jekyll](https://jekyllrb.com/docs/front-matter/)
- [DocFX](https://dotnet.github.io/docfx/spec/metadata_format_spec.html#3-work-with-metadata-in-markdown)
- Pandoc only has [title blocks](https://pandoc.org/MANUAL.html#extension-pandoc_title_block) right now, but are [currently implementing](http://blog.martinfenner.org/2013/06/21/what-flavor-is-scholarly-markdown/#comment-945513935) the YAML header.
- [Hugo](https://gohugo.io/content-management/front-matter/) optionally supports TOML with `+++` and JSON with `{` and `}`
- [Grav](https://learn.getgrav.org/16/content/headers)
- [MkDocs](https://www.mkdocs.org/user-guide/writing-your-docs/) supports YAML and Multimarkdown-style.
- [ScholarlyMarkdown](http://scholarlymarkdown.com/Scholarly-Markdown-Guide.html#including-metadata)

Hope this helps!

**Comment by RobertDober** [comment]
Sorry to turn you down, but with no major implementation supporting this, and with zero added value for `ex_doc` I have to reject this feature.

However why not create a nice little hex project wrapping `Earmark` in order to achieve this.

This would put no burden on `Earmark`  or  `ex_doc` while providing exactly the service you ask for.

**Comment by surprisetalk** [comment]
No worries! Thanks for the consideration.

And once again, thanks again for contributing to such a wonderful library!

**Comment by fschoenfeldt** [comment]
FYI, there's a tool for Elixir: https://github.com/sebastiandedeyne/yaml_front_matter
