### ISSUE TITLE
Documentation not up to date

### ISSUE THREAD

**Issue by AcMaSven** [pragdave/earmark#241]
The linked documentation on hexdocs.pm is not up to date with the last release. You can see here https://github.com/pragdave/earmark/blob/7cab6b3b059ada2bf0a4560038f4761c6202262b/lib/earmark.ex#L294 that as_html returns {:ok,html_doc,messages}. But the documentation on hexdocs says it returns {:ok,html_doc} https://hexdocs.pm/earmark/Earmark.html#as_html/2 .

**Comment by RobertDober** [comment]
Thank you for reporting this, it is already fixed.
