### ISSUE TITLE
Add Math tags support

### ISSUE THREAD

**Issue by mysteriouspants** [pragdave/earmark#25]
A certain [Markdown-with-benefits parser](http://kramdown.gettalong.org/) supports parsing mathematical content like so:

```
This demonstrates inline $$\LaTeX$$ support, and the following demonstrates block support.

$$A = \frac{1}{2}\int_{a}^{b}\left( \left[f(\theta)\right]^2 - \left[g(\theta)\right]^2 \right)\,d\theta.$$
```

This is then emitted in a format that a JavaScript tool called [MathJax](http://www.mathjax.org/) can process into lovely typeset equations. The alluded-to Markdown parser accomplishes this by emitting code like the following:

```
<p>This demonstrates inline <script type="math/tex">\LaTeX</script> support, and the following demonstrates block support.

<script type="math/tex; mode=display">A = \frac{1}{2}\int_{a}^{b}\left( \left[f(\theta)\right]^2 - \left[g(\theta)\right]^2 \right)\,d\theta.</script>
```

It's a neat feature and I use it a lot. I've been [attempting to add the feature myself](https://github.com/mysteriouspants/earmark/tree/maths-support), but my regex-fu isn't very strong and so I've really only succeeded in making a bit of a mess. I'm still super-new to Elixir, so if you have any suggestions or know what I'm doing wrong, I'd greatly appreciate the help!

**Comment by pragdave** [comment]
Chris:

I'm a big fan of LaTeX math. 

I wonder though if it would be better to find a more generic way to support it. If Earmark supported plugins, we could have an extension syntax which could invoke any of a number of different plugins.

For example, the math extension could register itself and declare it was using the "$" prefix. Then you could write

    «$ 1 \over 2 »

or somesuch syntax to invoke it.

What do you think?

**Comment by mysteriouspants** [comment]
I think plugins are a great idea, particularly when you consider that plugins could be added on a domain-specific basis: ExDoc could add a syntax for linking to other documentation similar to C#'s `<see cref=""/>` feature for linking to other documented code elements; Wikis could add their own wikilinks and TOCs; I think it opens the door to all kinds of fun things.

How might one go about making Earmark pluggable? I gave it some thought while on the treadmill and it seems to me that we'd take all the existing tags and turn them into plugins that are used by default. Programmers could then supply a modified list of plugins (including their own!) when they invoke Earmark.

I've been trying to think through how to implement this, but I keep coming up with things that feel rather object-oriented (which is probably out of place in Elixir). My thought was to define a kind of protocol that a plugin must implement. Plugins are passed around as structs which have function members which contain the logic to do things like match against what they contain.

It also seems to me, and stop me if this is going too far, that it would be nifty to shim a layer in between the parsed result and the renderer so that we could write different renderers, so we could create, say, PDF documents in addition to HTML documents. I could see that being super nifty in contexts like generating documentation in a handy downloadable PDF so you could have everything with you on plane trips and other such situations.

Regarding the syntax, I very much favor the double-dollar-sign syntax because it's harder to invoke in regular text in which the `$`-character may be used in some other means. Escaping it all the time would be a pain.

**Comment by RobertDober** [comment]
Trying to play around with these ideas a little bit. Definitely for the plugin support.

**Comment by RobertDober** [comment]
@mysteriouspants `$`in the first col are rare, but `$$` might be more readable and is easier to type than `\$`, so I vote for `$$`too.

**Comment by RobertDober** [comment]
As #106 is now closed Math support shall be implemented in a plugin.
