### ISSUE TITLE
Packaging to Debian

### ISSUE THREAD

**Issue by rajasekharponakala** [pragdave/earmark#250]
Hey, any progress on the Debian packaging so far?, found this RFP in the Debian bugs.

RFP bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=795501

**Comment by RobertDober** [comment]
I do not understand what you would like us to do? I guess you need to ask the Debian folks about this.

**Comment by rajasekharponakala** [comment]
@RobertDober, hi.
Yeah, you are right, just want to know if anyone from this project has worked

**Comment by RobertDober** [comment]
No we are not involved with Debian, sorry.
