### ISSUE TITLE
Support for Kramdown's markdown="1" flag

### ISSUE THREAD

**Issue by logicmason** [pragdave/earmark#251]
There are many cases where it's useful to use markdown inside a block element. The way Kramdown handles this is with an attribute placed on the HTML element.

Example:
```kramdown
<div class="some-list-style" markdown="1">
- A nested list that can't be styled currently
-- sub list
--- one thing
--- another thing
-- other sub list
--- foo
--- bar
--- baz
</div>
```

https://kylebebak.github.io/post/mixing-markdown-html

**Comment by RobertDober** [comment]
I do not like this, but keep my mind and the ticket open.

Right now the parsers is written in a way that this will become extremely difficult to implement.
But if, and that is a big if, one day I rewrite the parser, I still do not believe that this is a good idea.

**Comment by logicmason** [comment]
I may be overly influenced by familiarity with Github pages and Jekyll. Is there another way of accomplishing this that I'm missing?

It seems like styling a list is a fairly mainstream use someone must have run into already.

**Comment by pragdave** [comment]
I've been using Kramdown for years (the Pragmatic Bookshelf toolchain uses
it), and I agree that being able to mix markdown and HTML block elements is
useful.

However, I also find the Kramdown approach to be problematic. The semantics
of nested blocks is unclear, and  things such as indentation are
inconsistent.'

So while I'd love to see the ability to mix the two, I don't think the
Kramdown way is the way to do it. I'd rather find a syntax to integrates
the two more seamlessly. I just have no idea what that would look like :)


Dave

**Comment by RobertDober** [comment]
Hmm if we had an explicit way to express a `<div>` we could annotate it with an IAL

That would be something like

```markdown
~
  - item1
  ...
  - itemn
~{:.some-list-style}   
```
**only** available by setting an option (e.g. `explicit_divs: true`) to protect ex_doc.

BTW @pragdave do I have a green light for the release of 1.3.3? I sent you a mail a couple of weeks ago.

**Comment by pragdave** [comment]
Oh, sorry. Of course...

**Comment by logicmason** [comment]
> Hmm if we had an explicit way to express a `<div>` we could annotate it with an IAL
> 
> That would be something like
> 
> ```gfm
> ~
>   - item1
>   ...
>   - itemn
> ~{:.some-list-style}   
> ```
> 
> **only** available by setting an option (e.g. `explicit_divs: true`) to protect ex_doc.

That's almost exactly what I'm doing now as a work-around in a wrapper. I'm using `::div` to open it and `:/div` to close it like this:

```
::div.class1.class2
- list
-- sub list
--- one thing
--- another thing
-- other sub list
--- foo
--- bar
:/div
```

Being able to use IAL is more flexible and an improvement over this, though.
