### ISSUE TITLE
Markdown links with URL as text break with pure_links enabled

### ISSUE THREAD

**Issue by sn3p** [pragdave/earmark#254]
When parsing markdown links where the text is an URL:

```ex
"[https://github.com](https://github.com)"
|> Earmark.as_html!(pure_links: true)
```

It outputs nested links:

```html
<p><a href="https://github.com"><a href="https://github.com">https://github.com</a></a></p>
```

**Comment by RobertDober** [comment]
Nice catch thank you

I believe that this double link actually is probably not much of an issue in most browsers, but nevertheless I'll fix it ASAP.

**Comment by sn3p** [comment]
Thank for fixing!

> I believe that this double link actually is probably not much of an issue in most browsers, but nevertheless I'll fix it ASAP.

You're right, links will not rendered nested in most browsers, instead it renders an additional empty link which doesn't take any space. But in our case we render an additional "external link" icon. It was rendering twice so that's how I find out, otherwise I probably wouldn't have noticed 😄

**Comment by RobertDober** [comment]
Aha would you need a release? Or can you work from master, which we keep green as much as we can!

**Comment by sn3p** [comment]
> Aha would you need a release? Or can you work from master, which we keep green as much as we can!

Release would be great, but guess we could work from master for a bit 👍

**Comment by RobertDober** [comment]
ok @pragdave I know this would be a tiny release but I do not see why not helping out our users. Do I have a go?

**Comment by pragdave** [comment]
You _always_ have a go. It's your project :)

**Comment by RobertDober** [comment]
Thank you @pragdave, your guidance is always appreciated!

**Comment by RobertDober** [comment]
@sn3p released

**Comment by sn3p** [comment]
Many thanks @RobertDober !!
