### ISSUE TITLE
Align Needed Elixir Version with ex_doc

### ISSUE THREAD

**Issue by RobertDober** [pragdave/earmark#256]
Right now [ex_doc v0.21.2](https://github.com/elixir-lang/ex_doc/blob/v0.21.1/mix.exs) requireves Elixir '~> 1.7'

Given that `ex_doc` is our primary customer and that `Earmark 1.3` is stable I'd like to increase the needed Elixir version for `Earmark 1.4` to `1.7` too.

Ok with your philosophy @pragdave ?

**Comment by pragdave** [comment]
Yeah, that sounds like a good plan

**Comment by RobertDober** [comment]
Done in expose_ast
