### ISSUE TITLE
 Deprecate  `sanitize` option? [was: Add documentation for `sanitize` option]

### ISSUE THREAD

**Issue by sn3p** [pragdave/earmark#257]
README [says](https://github.com/pragdave/earmark#security):

> **Security**
Please be aware that Markdown is not a secure format. It produces HTML from Markdown and HTML. It is your job to sanitize and or filter the output of Earmark.as_html if you cannot trust the input and are to serve the produced HTML on the Web.

But it doesn't mention the `sanitize` option. Seems that it escapes HTML?

```ex
Earmark.as_html!("<b>bold?</b>")
"<p><b>bold?</b></p>"
```

```ex
Earmark.as_html!("<b>bold?</b>", sanitize: true)
"<p>&lt;b&gt;bold?&lt;/b&gt;</p>"
```

**Comment by RobertDober** [comment]
Oh that is great, I completely had forgotten about that option.

I am however quite sure that it will not be sufficient in its current state...

```elixir
iex(10)> Earmark.as_html!("<b>bold?</b>", sanitize: true)
"<p>&lt;b&gt;bold?&lt;/b&gt;</p>\n"
iex(11)> Earmark.as_html!("<div><b>bold?</b></div>", sanitize: true)
"<div><b>bold?</b></div>"
```

I guess I'll rather deprecate the option than to fix it, IIUC most markdown converters do not sanitize.

That said, it would be a great tool to have but reliable sanitization is a small and moving target and I prefer to say clearly that you must not trust your input, instead of giving the users a __false__ sense of security.

**Comment by sn3p** [comment]
Agree. Deprecating the `sanitize` option sounds like the best course of action.
Also escaping HTML alone is not enough, for example this is still allowed:

```ex
Earmark.as_html!("[alert](javascript:alert('XSS');)")
"<p><a href="javascript:alert(&#39;XSS&#39;);">alert</a></p>"
```

marked.js did the same, they added a deprecation note for the `sanitize` option [in the docs](https://marked.js.org/#/USING_ADVANCED.md#options) and added some recommendations.

I've been using [html_sanitize_ex](https://github.com/rrrene/html_sanitize_ex) and there is also [phoenix_html_sanitizer](https://github.com/elixirstatus/phoenix_html_sanitizer).

What would your recommendation be?

**Comment by sn3p** [comment]
By the way, the reason I'm still using the `sanitize` options is that it escapes HTML.
[html_sanitize_ex](https://github.com/rrrene/html_sanitize_ex) only strips HTML but [has no option to escape](https://github.com/rrrene/html_sanitize_ex/issues/37).

**Comment by RobertDober** [comment]
Good to know that there are tools for the job in question.
