### ISSUE TITLE
Wrong curly parens if surrounded text ends with a tag.

### ISSUE THREAD

**Issue by mschae** [pragdave/earmark#26]
Hey Dave,

unfortunately we stumbled upon this bug:

```Elixir
  test "closing parens" do
    result = Earmark.to_html ~s(a "**test**")
    assert result == "<p>a “<strong>test</strong>”</p>\n"
  end
```

That test should pass (I think) but it doesn't as the result of this is:

```
<p>a “<strong>test</strong>“</p>\n
```

What happens is that `Earmark.Inline.smartypants/1` receives the following snippets: `a "` `test` `"`. The last snippet is matched to `“` rather than `”`.

Unfortunately that's where I am striking out right now...

**Comment by pragdave** [comment]
Hmm.. tricky.

Let me think about that.

In the meantime, a workaround would presumably be to move the quotes inside the bold?

**Comment by mschae** [comment]
Thanks for looking into this Dave!

Definitely a workaround but it's easy to come up with examples where that's not an option. Any way I can help with the fix?

**Comment by RobertDober** [comment]
Hi 
I am trying to figure this out ;).
Seems to me that the fix would be the same for this problem, if it is one, not sure.

```elixir
Earmark.to_html ~s(a " test ")  # --> "<p>a “ test “</p>\n"
```

If that is the case a more context aware `Earmark.Inline.smartypants/1` could do the trick, right or do I miss some block element context?

KR

**Comment by pragdave** [comment]
I dropped the ball on this. I just commuted a failing test, and I'll have a
look for a fix. I someone finds one first, please let me know :)

**Comment by pragdave** [comment]
I've push a somewhat tacky fix

**Comment by RobertDober** [comment]
I wanted to fix this `test/inline_test.ex ==> test/inline_test.exs` I'll make a PR for this but no issue unless you want one for your workflow
