### ISSUE TITLE
Remove Plugins

### ISSUE THREAD

**Issue by RobertDober** [pragdave/earmark#261]
Followup of #236 to be removed in 1.4

**Comment by redrabbit** [comment]
I'd like to customise/extend Earmark to support different things. For example, auto-link specific characters (`@` mention) or support emojis.

> if anyone wants them, they could be implemented around Earmark instead of in Earmark.

What would be the best way to customise the output outside of Earmark?

Let's say to support emojis, i'd like to implement a simple syntax alà `:+1:`. Now this still needs to be escaped when in `<code>` or `<pre>` blocks.

**Comment by RobertDober** [comment]
I am working on exposing the AST right now, I hope to release an experimental AST exposure in 1.3.6.

A plugin was not really suited for your use case anyway, as you would have needed to preprocess the input and then recursively call `as_html` but as you pointed out correctly the preprocessor needed intimite knowledge of the document structure.

That is where AST exposure shines, traverse the AST tree, e.g. with my `Traverse` lib, :blush: setting a flag when inside code and depending on your flag replacing the :+1: ...

I hope that the AST exposure will create some libs using Earmark

**Comment by chazsconi** [comment]
@RobertDober great that you now have the AST exposed, but after manipulating the AST is there a way to then render it as HTML?

**Comment by RobertDober** [comment]
@chazsconi not yet
I guess I have to open a FR
