### ISSUE TITLE
Additional <colgroup><col><col></colgroup> block after parsing a table

### ISSUE THREAD

**Issue by milmazz** [pragdave/earmark#262]
Assume this table from the Elixir [Compatibility and Deprecations](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/pages/Compatibility%20and%20Deprecations.md) guide as an input example:

```markdown
Elixir version | Support
:------------- | :-----------------------------
1.10           | Development
```

Earmark produce the following output as HTML:

```elixir
iex(3)> table = """
...(3)> Elixir version | Support
...(3)> :------------- | :-----------------------------
...(3)> 1.10           | Development
...(3)> """
"Elixir version | Support\n:------------- | :-----------------------------\n1.10           | Development\n"
iex(4)> Earmark.as_html!(table, gfm: true)
"<table>\n<colgroup>\n<col>\n<col>\n</colgroup>\n<thead>\n<tr>\n<th style=\"text-align: left\">Elixir version</th><th style=\"text-align: left\">Support</th>\n</tr>\n</thead>\n<tr>\n<td style=\"text-align: left\">1.10</td><td style=\"text-align: left\">Development</td>\n</tr>\n</table>\n"
```

The problem with the previous output is the fragment `<colgroup><col><col></colgroup>`, why is that block needed?

When ExDoc produces an EPUB document from the Elixir source code I got the following error after reviewing the EPUB document with [epubcheck](https://github.com/w3c/epubcheck):

```
ERROR(RSC-005): doc/elixir/Elixir.epub/OEBPS/compatibility-and-deprecations.xhtml(19,6): Error while parsing file: element "col" not allowed here; expected the element end-tag
```

I did a quick comparison with other markdown parsers using [babelmark 3](https://babelmark.github.io/?text=Elixir+version+%7C+Support%0A%3A-------------+%7C+%3A-----------------------------%0A1.10+++++++++++%7C+Development) and none of them introduce the block `<colgroup><col><col></colgroup>`.

**Comment by RobertDober** [comment]
Seems indeed that `<colgroup>` is completely useless, I'll look into removing it...

**Comment by milmazz** [comment]
@RobertDober Thanks for taking care of this issue 👍

**Comment by RobertDober** [comment]
No problem, just out of curiosity, I removed it because it was useless, however it seems it was perfectly legal HTML5, is this correct?

**Comment by milmazz** [comment]
@RobertDober ExDoc can produce HTML documents like the ones you normally see on [hexdocs](https://hexdocs.pm/elixir/Kernel.html). ExDoc is also able to produce EPUB documents.

The _Content Documents_ of an EPUB file, which internally is a zip file that follows a given structure according to its specification, are also HTML documents, but in this particular case the document must conform with the XHTML syntax and those documents should use the extension `.xhtml`. Given that we're talking here about XHTML documents, we must also meet the conformance constraints for XML docs as well. So, having a non-closed `<col>` element tag is not allowed in this context.

Visually this means the following:

1. `ex_doc` using an older version of `earmark`:

<img width="520" alt="Screen Shot 2019-08-02 at 9 46 15 AM" src="https://user-images.githubusercontent.com/34700/62378695-ff5b8880-b50a-11e9-9ba0-3f3abf36b2b3.png">

2. `ex_doc` using the most recent version of `earmark`:

<img width="485" alt="Screen Shot 2019-08-02 at 9 47 15 AM" src="https://user-images.githubusercontent.com/34700/62378753-231ece80-b50b-11e9-898f-3f190c06d101.png">

HTH

**Comment by RobertDober** [comment]
:sweat: 
Earmark is **not** XHTML compliant
:cry:

```
iex(13)> Earmark.as_html!("a\\\nb")             
"<p>a<br>\nb</p>\n"
```

**Comment by RobertDober** [comment]
c.f. #266

**Comment by pragdave** [comment]
Let's not lose HTML5 compatibility, though...

**Comment by RobertDober** [comment]
@pragdave I was worried about that at first too, but to my surprise I discovered that the [HTML5 style guide](https://www.w3schools.com/html/html5_syntax.asp) encourages max XHTML compatibility.

I guess w/o having checked the whole code base is to change `<br>` to '<br />` , `<img ...>` to `<img... />` and so on.

As much as I personally hate these `.. />` suffixes.

That said I agree with you in case of an incompatibility between HTML5 and XHTML, HTML5 will be the winner, I hope @milmazz you understand, that is by no means by disrespect for the wonderful work you are doing with epub.

**Comment by milmazz** [comment]
@RobertDober on the contrary, I'm happy to see that you'll increase the compatibility with XHTML. Thanks for your hard work too!

-------- Original Message --------
