### ISSUE TITLE
Make HTML conformant to the W3C Style Guide

### ISSUE THREAD

**Issue by RobertDober** [pragdave/earmark#266]
This will make our output better suited for other tools, e.g. epub.

Reference: https://www.w3schools.com/html/html5_syntax.asp

**Comment by jaimeiniesta** [comment]
Hi! 👋 

Please remember that the W3Schools is not the W3C!

The W3C Validator now recommends that trailing slashes are avoided for void elements, I've opened a PR here:

https://github.com/pragdave/earmark/pull/460
