### ISSUE TITLE
Indented lines within Lists

### ISSUE THREAD

**Issue by eksperimental** [pragdave/earmark#27]
There is a bug in the parser,
you can see it here
http://elixir-lang.org/docs/master/elixir/File.html#read/1
https://github.com/elixir-lang/elixir/blob/e3e8aec7bfa3ca8a060f679f9580bc7f40ae0a78/lib/elixir/lib/file.ex#L219-L225

the problem happens when inside a list (I guess it happens with both ordered and unordered), there is a line that has been indented with 4 spaces or more, the line will be takes as codeblock,

[I have checked babelmark2 and the main engines deal with this,](http://johnmacfarlane.net/babelmark2/?text=*+%60%3Aenoent%60++-+the+file+does+not+exist%0A*+%60%3Aeacces%60++-+missing+permission+for+the+file+or+one+of+its+parents%0A*+%60%3Aeperm%60+++-+the+file+is+a+directory+and+user+is+not+super-user%0A*+%60%3Aenotdir%60+-+a+component+of+the+file+name+is+not+a+directory%3B%0A+++++++++++++++on+some+platforms%2C+enoent+is+returned+instead%0A*+%60%3Aeinval%60++-+filename+had+an+improper+type%2C+such+as+tuple)

**Comment by milmazz** [comment]
@eksperimental This issue report appears that can be closed because the problem was in Elixir's documentation, right?

**Comment by pragdave** [comment]
Yes
