### ISSUE TITLE
Missing GFM table support

### ISSUE THREAD

**Issue by chengyin** [pragdave/earmark#278]
Earmark requires extra space around `|`, while GitHub doesn't:

```markdown
#### works in earmark

State | Abbrev
----- | ------
Texas | TX


#### doesn't work in earmark

State | Abbrev
------|-------
Texas | TX
```

GitHub Render test:

#### works

State | Abbrev
----- | ------
Texas | TX

#### doesn't work

State | Abbrev
------|-------
Texas | TX

**Comment by RobertDober** [comment]
Thank you for reporting this.

We are definitely going for maximal GFM compatibility however this seems a minor difference to me, is this an issue for you?

I will definitely keep this open but assign it low priority for now.

If this is a problem for your application, please tell me more.

Thx again

**Comment by chengyin** [comment]
Hey Robert, thank you for responding! Our application allows importing markdown files, so the input is entirely out of our control. It does present a problem when the user expects to the same render result as in GitHub.

FYI, both this bug and #279 were caught through https://github.com/louthy/language-ext/blob/master/README.md.

**Comment by RobertDober** [comment]
Ok if I can adapt the table behavior to the GFM behavior I will, however this was never foreseen to be done,  if it breaks old behavior I am afraid you will be out of luck, but why be pessimistic.

**Comment by RobertDober** [comment]
I have been giving this some thought.
I am afraid of backwards incompatibilities and have therefore implemented only with the new option `gfm_tables`

```elixir
      markdown = "a|b\n-|-\nd|e\n"
      html     = "<table>...\n" 
      messages = []

      assert as_html(markdown, gfm_tables: true) == {:ok, html, messages}
```
I hope that will be good for you.

Hopefully GFM compatibility will advance and with issuing deprecations before adapting this behavior as default we might get to this as a default
