### ISSUE TITLE
Wrong render result when setting syntax highlight language to `C#`

### ISSUE THREAD

**Issue by chengyin** [pragdave/earmark#279]
Using `C#` as the syntax highlight language will lead to wrong render result.

<pre>
markdown = """
  ```C#
  var optional = Some(123);
  ```
  """

Earmark.as_html!(markdown)
</pre>

Will produce inline code with C# in content:
`<p><code class="inline">C# var optional = Some(123);</code></p>`

In GitHub it renders correctly:

```C#
var optional = Some(123);
```

**Comment by RobertDober** [comment]
Well you should not use `C#`...

**just kidding**.  Thank you for this I will try to fix this soon, hopefully low hanging fruit.
