### ISSUE TITLE
Tag latest version

### ISSUE THREAD

**Issue by olgeni** [pragdave/earmark#29]
Hi,

Version 0.1.17 is listed on hex.pm, but the latest tag here is v0.1.8. Was anything left uncommitted?

It would be great to have the latest code available. Thanks!

**Comment by pragdave** [comment]
I think it's all up to date. I normally don't tag releases. I did for a little while here as an experiment, but it didn't stick :)

**Comment by olgeni** [comment]
Do you know where hex.pm version numbers come from? :)

**Comment by pragdave** [comment]
mix.ex

**Comment by olgeni** [comment]
There it is. Thanks!
