### ISSUE TITLE
Rendering Elixir code inside Markdown

### ISSUE THREAD

**Issue by jdanielnd** [pragdave/earmark#290]
We're using Earmark to render markdown, but one thing we often need to do is **include helper elixir functions** to encapsulate recurrent present logic. This behavior is inspired by [shortcodes](https://gohugo.io/content-management/shortcodes/) from [Hugo](https://gohugo.io/).

For example, we want to link external contents with a specific class, so that our tracking JS know it should track those clicks.

```
### Title

This is a text with a <%= external_link %{text: "link" href: "#some_where" } %>
to some where.
```

And have helper functions defined elsewhere

```
defmodule SimpleBlog.Helper do
  
  def external_link(params) do
    "<a href=\"#{params.href}\" class=\"external-link\">#{params.text}</a>"
  end

end
````

We're using EEx.eval_string, and passing the helper functions, to make this possible.

```
markdown
|> EEx.eval_string([], functions: [{SimpleBlog.Helper, [external_link: 1]}])
|> Earmark.as_html
```

We're encapsulating this logic, to make it simpler to import EEx functions and render Elixir code everywhere.

I'm opening this issue to ask if this is a feature that could be on Earmark, or if we should build it as an extension using Earmark, but in a separate lib.

**Comment by jdanielnd** [comment]
Simple example: https://github.com/jdanielnd/eex_markdown

**Comment by RobertDober** [comment]
Sorry as I fail to understand why your example above needs any changes in Earmark I am closing this issue now. Feel free to reopen if there is anything I missed.
