### ISSUE TITLE
Heading id:s anchors

### ISSUE THREAD

**Issue by jmn** [pragdave/earmark#295]
Would it be possible to have `Earmark.as_html("##Foo")` generate `<h2 id="foo">Foo</h2>` so you can navigate the document to section headings (e.g. /document.html#foo"). Pandex (Pandoc) currently does this.

**Comment by RobertDober** [comment]
I like the idea. But I need to give it some thoughts, because I am very vulnerable to feature creep.
Another point is that we risk creating conflicting id's what would you think about the alternative of being GFM compliant https://babelmark.github.io/?text=%23%23+hello and therefore generating

```html
  <a id="user-content-hello" class="anchor" href="#hello" aria-hidden><span aria-hidden class="octicon octicon-link"></span></a>hello
```
That would also be better because as far as I understand @josevalim is rather pro GFM compliance and ex_doc is just our main customer :blush:

I guess I would lose the `<span>` though.

**Comment by josevalim** [comment]
We already do it for ExDoc, so if it is added, we would need to make it opt-in or opt-out to not break our references. We pretty much have to namespace all of our ids by the module or function name, because the chance of conflicts is high.

**Comment by RobertDober** [comment]
Thx for the update  @josevalim. So there _could_ be an option for that, but there are a great many already.... hmm I still see the value of the feature and it is easy to implement, but code is 
**always** a liability. 

Would using the evolving API with `as_ast |> your_filter |> transform` be an option @jmn ?

I'd love to see people develop that kind of filter for all to use and to take some burden off Earmark.

**Comment by RobertDober** [comment]
Just an idea. After 1.5 is released it would be nice to create a hex package EarmarkFilters which would test their filters against `Earmark.Transform.transform`. I _could_ own such a package but would surely prefer to be a humble contributor if needed.

**Comment by jdmarshall** [comment]
Markdown cheat sheet says that the syntax 'should' be 

### My Great Heading {#custom-id}

Which of course does not work with Earmark.

**Comment by RobertDober** [comment]
This would be nice :blush:

again these are reasonabe ideas, for which I do not have reasonable time alas.

Actually adding yet another option (`auto_anchor_ids: false`)  would not be too much work for now, I'll give it a thought

concerning the syntax mentioned by @jdmarshall  would this be something possible in [Earmark Parser](https://github.com/RobertDober/earmark_parser) ? Should again be protected with an option I am afraid as it _might_ break some ex_doc although would be nice to be _standard_ by default, thoughts @josevalim ?
