### ISSUE TITLE
backticks are not interpreted inside HEADINGS

### ISSUE THREAD

**Issue by eksperimental** [pragdave/earmark#30]
The code in question:

```md
## Differences from `defmodule`
```

earmark will convert the code above to:

```html
<h2>Differences from `defmodule`</h2>
```

while the rest of the implementations will do:

```html
<h2>Differences from <code>defmodule</code></h2>
```

We use this feature in the [Elixir website itself](http://elixir-lang.org/getting-started/case-cond-and-if.html#if-and-unless). I was just trying to use it in ExDoc, and bumped into this.

Just for the record, 100% of the implementation in bablemark2 are intepreting what's inside the backticks as code http://johnmacfarlane.net/babelmark2/?normalize=1&text=%23%23+Differences+from+%60defmodule%60%0A%0AThis+is+the+text

**Comment by RobertDober** [comment]
Hmm Backticks seem just to be an example for **all** inline markup in Headers. Again as a reference

http://johnmacfarlane.net/babelmark2/?text=%23%23+Valid+for+all+_inline_+markup

while

```elixir
iex(42)> Earmark.to_html "# Hello _World_"
"<h1>Hello _World_</h1>\n"

```

**Comment by eksperimental** [comment]
thanks a lot @RobertDober
