### ISSUE TITLE
Crash on certain type of message

### ISSUE THREAD

**Issue by OvermindDL1** [pragdave/earmark#308]
Running the minimized code of:
```elixir
Earmark.as_ast("<a>a")
```

Crashes with:
```
13:47:26.251 [error] Task #PID<0.10017.6> started from #PID<0.10012.6> terminating
** (RuntimeError) Internal Error, must not call render_html_block/1 without a leading HTML Tag
    (earmark) lib/earmark/ast/renderer/html_renderer.ex:12: Earmark.Ast.Renderer.HtmlRenderer.render_html_block/1
    (earmark) lib/earmark/ast_renderer.ex:46: Earmark.AstRenderer.render_block/2
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<4.124868479/0 in Earmark.pmap/3>
    Args: []
```

In addition doing `Earmark.as_ast("<a>")` is returning `{:error, [{"a", [], []}], [{:warning, 1, "Failed to find closing <a>"}]}`, when as can be seen on github here as well works fine, it just auto-closes it, is there an option to override that in earmark to act like github's markdown?

**Comment by OvermindDL1** [comment]
But yeah, some people are having fun crashing one of my bots because of this bug now...  >.>

**Comment by RobertDober** [comment]
That I am sorry about and I shall try to find the time to fix this soon.
Thank you for adopting as_ast early.

Concernig the "<a>" well I am open minded (could not resist, sorry) about it, but I need to look into it, I will open a ticket for this as it is low prio, while this one is high prio.

**Comment by OvermindDL1** [comment]
Yeah the `<a>` and so forth not being an error is minimal (it happens with any `<blahblah>` style tag), just a nice thing, the crash is the big thing here.  ^.^

**Comment by RobertDober** [comment]
Seems you are using 1.4.1, this is fixed in 1.4.2

Can you confirm?

**Comment by OvermindDL1** [comment]
Ah I thought I was updated, I updated not long ago, my bad, it's fixed.  ^.^

Sorry for the noise!

**Comment by RobertDober** [comment]
No problem
