### ISSUE TITLE
Code fence with more than 3 backticks

### ISSUE THREAD

**Issue by chulkilee** [pragdave/earmark#309]
To include code with three backticks, GFM allows wrapping the code with more than three backticks.

From https://github.github.com/gfm/#fenced-code-blocks

> A code fence is a sequence of at least three consecutive backtick characters (`) or tildes (~).

For example:

`````
````elixir
defmodule Foo do
  @moduledoc """
   Foo bbar

   # Example

   ```elixir
      defmodule MyFoo
      end
   ```
  """
end
````
`````

This is rendered in GFM  as follows:

````elixir
defmodule Foo do
  @moduledoc """
   Foo bbar

   # Example

   ```elixir
      defmodule MyFoo
      end
   ```
  """
end
````

For now, I circumvent it with using `~~~` instead of using four backticks.

```elixir
"````elixir\n```\ninside\n```\n````\n" |> Earmark.as_html!(gfm: true)
"<p><code class=\"inline\">elixir ``` inside ```</code></p>\n"

"~~~elixir\n```\ninside\n```\n~~~\n" |> Earmark.as_html!(gfm: true)
"<pre><code class=\"elixir\">```\ninside\n```</code></pre>\n"
```

---

(originally reported to https://github.com/elixir-lang/ex_doc/issues/1108)

**Comment by RobertDober** [comment]
I was not aware of this, thanks for the issue.
It should be easy to implement.

**Comment by RobertDober** [comment]
> For now, I circumvent it with using ~~~ instead of using four backticks.

That is because there are two bugs here as we do not check for the _indented with no more than 3 spaces_ either. :cry:

**Comment by OvermindDL1** [comment]
I'm curious where `~~~` comes from?  Traditionally in markdown the `~` is used for things like \~strikeout\~ for ~strikeout~ and so forth.  I've never seen it used for code fences?

**Comment by RobertDober** [comment]
I am afraid not to know that answer. Gruber not even mentions ~```~ and I ignore the influences of markdown, maybe someone can enlighten us on the elixir forum?

**Comment by chulkilee** [comment]
@OvermindDL1  I didn't know that but got it when reading GFM doc at https://github.github.com/gfm/#fenced-code-blocks

> A code fence is a sequence of at least three consecutive backtick characters (`) or tildes (~).

**Comment by OvermindDL1** [comment]
@chulkilee Ah, that's a github'ism!  Commonmark took a lot from GFM.  Interesting, I wonder why when repeated \`'s are so simple...

**Comment by RobertDober** [comment]
Both are a pain to type, when you are French, LOL
