### ISSUE TITLE
pony: support an include feature

### ISSUE THREAD

**Issue by RichMorin** [pragdave/earmark#316]
I would like Earmark to support some form of include feature. Problem is, there doesn't seem to be any accepted standard for the syntax. Here, for example, is the syntax used by Jekyll:

    {% include_relative filepath %}

And here is the syntax for DocFX Flavored Markdown:

    [!include[<title>](<filepath>)]

Meanwhile, I plan to add a syntax extension for this. So, I'd like to know what syntax, if any, Earmark might use.  Comments?

**Comment by pragdave** [comment]
Be really careful here. Earmark is used for server side rendering, and
allowing files to be included could be a big security hole...

**Comment by RichMorin** [comment]
> On Dec 17, 2019, at 15:42, Dave Thomas <notifications@github.com> wrote:
> 
> Be really careful here. Earmark is used for server side rendering, and
> allowing files to be included could be a big security hole...

Indeed, and I'm using it in exactly that use case.  However, I think I have
that sort of issue under control.  If something is implemented in Earmark,
a warning of some sort in the docs might be appropriate.

-r

**Comment by pragdave** [comment]
Why not just write a separate preprocessor?

**Comment by RichMorin** [comment]
> Why not just write a separate preprocessor?

That's kind of what I'm doing at the moment.  I already support a small number of extensions to Markdown and TOML; I'll just add this to the repertoire:

http://cfcl.com:64000/item?key=Areas/Content/HowTos/PA_Extensions/main.toml

-r

**Comment by RobertDober** [comment]
I am afraid I am with @pragdave on this. Earmark shall remain as lean as possible and if you have been following some other issues we are really pushing this kind of functionality towards external tools.
IMHO Earmark shall do one thing, and that as well as possible, converting markdown to html.

BTW I have the feeling that supporting ex_doc must remain the primary goal even if we are happy that it is used in other applications. Do you agree Dave?

**Comment by pragdave** [comment]
I do.

**Comment by RichMorin** [comment]
Understood.  For the record, I have decided to support Jekyll's include syntax and (until I come up with a different use case) to restrict included files to the local directory.

-r
