### ISSUE TITLE
as_ast and escaping

### ISSUE THREAD

**Issue by wojtekmach** [pragdave/earmark#333]
Currently we have the following:

```elixir
iex> Earmark.as_html("<")
{:ok, "<p>&lt;</p>\n", []}

iex> Earmark.as_ast("<")
{:ok, [{"p", [], ["<"]}], []}
```

should as_ast escape too, if not as default perhaps at least as an option?

worth mentioning the ast->html does escaping:

```elixir
iex> Earmark.Transform.transform([{"p", [], ["<"]}])
"<p>\n  &lt;\n</p>\n"
```

We're using `as_ast` (very useful <3) in ExDoc and we ended up manually converting ast to html bypassing the transformer (it's adding extra whitespace as above) and thus we need to manually escape too.

**Comment by wojtekmach** [comment]
Turns out it's better not to escape for ExDoc after all, we _want_ e.g. this unescaped:

```elixir
iex(1)> Earmark.as_ast("<<>>/1")
{:ok, [{"p", [], ["<<>>/1"]}], []}
```

so that we can process it later.

**Comment by RobertDober** [comment]
> We're using as_ast (very useful <3) in ExDoc and we ended up manually converting ast to html 
> bypassing the transformer (it's adding extra whitespace as above) and thus we need to manually 
> escape too

I was thinking about this and opened an issue #329 I did not know that you are *already* using `as_ast` it was not supposed to be stable before 1.5

**Comment by wojtekmach** [comment]
Technically we're not using it _yet_ but we have an open PR that we intend to merge soon: https://github.com/elixir-lang/ex_doc/pull/1132/files#diff-073b04a2864602a4686b68021fcf6ed5R40

We can probably wait for v1.5 but seems like the API is stable enough already?

One thing that @josevalim may have mentioned already that would be useful to us (but we're fine doing it ourselves) is returning tag names as _atoms_ (and not _strings_ as currently)

thanks for the heads up on #329, I'll keep an eye on it and I'd be keen on using that in ExDoc!

**Comment by RobertDober** [comment]
There was one change, on demand of @josevalim  #300 IIRC changing `{:comment, [], text}` to
`{:comment, text}` text being [string] (90% sure)
