### ISSUE TITLE
Children inside table cell have reversed order

### ISSUE THREAD

**Issue by robmadole** [pragdave/earmark#335]
With the following:

```markdown
| What              |
| ----------------- |
| This part is fine |
| This is `broken`  |
```

Passing this through `Earmark.as_html!/1` results in the `This is` and `broken` being reversed in order:

```html
      <td style="text-align: left;">
<code class="inline">broken</code>        This is 
      </td>
```

It looks like `Earmark.as_ast` is actually the culprit. I was able to `git bisect` it to 9127d91c0745a28d87bd61dd4484856e98d88cd7.

**Comment by RobertDober** [comment]
Yoda talk, what's wrong with that? ;)
However not everybody likes Star Wars, so we'll fix that.

On a side note, you are not reporting this bug against the released version so in general I would need to know where it occurred, however you got lucky on this one as I am already aware of the problem :blush:

Thank you for reporting this, and you are absolutely right, the AST parser gets some `Enum.reverse` wrong still...

**Comment by robmadole** [comment]
@RobertDober thanks for taking a look. At first, a feature I thought this was but that is the path to the Dark Side...so report this I must. 😉

And no worries on the release version comment. The reason I ran into this is because I reached for the AST parser to do some Dark Side mind manipulation converting `a` to `router-link` in a Vue app. I think the bug exists in the AST parser pretty far back.

**Comment by RobertDober** [comment]
... since the beginning and it is one of some road blockers for 1.5 where the AST will become official API,  but I guess you know all that.

**Comment by leandrocp** [comment]
I believe I came to the same bug here https://github.com/elixir-ecto/ecto_sql/pull/231#discussion_r436284459, I'm leaving this comment in case it helps and also to be notified so I can help testing a fix.

**Comment by robmadole** [comment]
Excellent! Getting excited for the 1.5 milestone.

**Comment by RobertDober** [comment]
1.4.6 :stuck_out_tongue:
