### ISSUE TITLE
Please publish the version 1.4.4 to hex.pm

### ISSUE THREAD

**Issue by razuf** [pragdave/earmark#338]
In my Elixir CI from Github: https://github.com/razuf/apa
I have the following warning:

Generated dialyxir app
warning: Code.load_file/1 is deprecated. Use Code.require_file/2 or Code.compile_file/2 instead
##[error]  mix.exs:106: Earmark.Mixfile.readme/1

warning: Mix.Local.path_for/1 is deprecated. Use Mix.path_for/1 instead
##[error]  mix.exs:90: Earmark.Mixfile.build_docs/1

If I look into this Repo I see its fixed in Release 1.4.4 but in hex.pm is only 1.4.3.

So please publish the new 1.4.4 to hex.pm and everything should be fine.

Thanks and Kind Regards
Ralph
by the way: Thanks for earmark |> a_good_piece_of_code !

**Comment by RobertDober** [comment]
Unfortunately 1.4.4 will not be released because we have changed the AST API and 1.5 is not ready yet.

**Comment by razuf** [comment]
Ah ok, thats why - it's fine for me to wait until 1.5 - it's only Warning in that CI - it's because of Elixir 1.10. ;-) 

Thanks for fast response!

Do you need any help for 1.5? Is it issue #311 ? AST Better doc ?

**Comment by razuf** [comment]
Maybe #317 ... but thats you are working on ... pease tell me if somewhere ...

**Comment by RobertDober** [comment]
If it only were that simple (to qoute a chageling) https://github.com/pragdave/earmark/milestone/22

**Comment by RobertDober** [comment]
Unfortunately for Earmark I am unsure when I can pursue the release of 1.5, I decided for this reason to backport the Mix issues and release 1.4.4

**Comment by razuf** [comment]
Thanks Robert! Good luck for you and 1.5.
