### ISSUE TITLE
** (FunctionClauseError) no function clause matching in Earmark.Helpers.AstHelpers.augment_tag_with_ial/2

### ISSUE THREAD

**Issue by wojtekmach** [pragdave/earmark#340]
```elixir
text = "* {:error, {IncompatibleUnitError, message}}"
Earmark.as_ast(text)
```

results in:

```
** (FunctionClauseError) no function clause matching in Earmark.Helpers.AstHelpers.augment_tag_with_ial/2

    The following arguments were given to Earmark.Helpers.AstHelpers.augment_tag_with_ial/2:

        # 1
        []

        # 2
        %{}

    Attempted function clauses (showing 1 out of 1):

        def augment_tag_with_ial([{t, a, c} | tags], atts)

    (earmark 1.4.4) lib/earmark/helpers/ast_helpers.ex:12: Earmark.Helpers.AstHelpers.augment_tag_with_ial/2
    (earmark 1.4.4) lib/earmark/ast/inline.ex:214: Earmark.Ast.Inline.converter_for_inline_ial/1
    (elixir 1.10.2) lib/enum.ex:3333: Enum.find_value_list/3
    (earmark 1.4.4) lib/earmark/ast/inline.ex:24: Earmark.Ast.Inline._convert/4
    (earmark 1.4.4) lib/earmark/ast_renderer.ex:153: Earmark.AstRenderer.render_block/3
    (earmark 1.4.4) lib/earmark/ast_renderer.ex:25: Earmark.AstRenderer._render/3
    (earmark 1.4.4) lib/earmark/ast_renderer.ex:143: Earmark.AstRenderer.render_block/3
    (earmark 1.4.4) lib/earmark/ast_renderer.ex:25: Earmark.AstRenderer._render/3
```

See https://github.com/elixir-lang/ex_doc/issues/1172 for more information.

**Comment by RobertDober** [comment]
Thank you for analysing and reporting this, I'll try to allocate some time for this.

**Comment by wojtekmach** [comment]
FWIW:

```diff
- * {:error, {IncompatibleUnitError, message}}
+ * `{:error, {IncompatibleUnitError, message}}`
```

both fixes the bug AND is prettier in the output! But yeah, the bug might be triggered in some other ways so worth fixing.

**Comment by RobertDober** [comment]
well that is great news as I have no time right now, ok for you to push it into 1.5, meaning, ETA uncertain?

**Comment by wojtekmach** [comment]
sounds good to me! since it's easy to fix in the user code I don't think it's a big deal.

**Comment by joaofcosta** [comment]
Hi 👋 

I'm also encountering this same issue and I'm currently unable to generate docs for a phoenix app. I've managed to trace this to a single doc and here's sample documentation which can trigger this bug:

```elixir
defmodule Sample do
  @doc """
  Creates a personal hello world message.

  ## Examples

  iex> Compensation.create("Mark", %{name: "Mark", age:
    27, info: %{email: "sample@gmail.com", phone:
      "123456789", address: "Around The Corner" } })
  {:ok, %User{...}}
  """
  def hello do
    :world
  end
end
```

It seems to be a very specific case because using the same documentation but moving things around slightly makes it work again, for example, the following documentation works:

```elixir
defmodule Sample do
  @doc """
  Creates a personal hello world message.

  ## Examples

  iex> Compensation.create("Mark", %{name: "Mark", age:
    27, info: %{email: "sample@gmail.com", phone: "123456789", address: "Around The Corner" } })
  {:ok, %User{...}}
  """
  def hello do
    :world
  end
end

```

But, maintaining the same formatting as the first example and just changing the second element of the tuple in the sample response also works:

```elixir
defmodule Sample do
  @doc """
  Creates a personal hello world message.

  ## Examples

  iex> Compensation.create("Mark", %{name: "Mark", age:
    27, info: %{email: "sample@gmail.com", phone:
      "123456789", address: "Around The Corner" } })
  {:ok, "Sample String"}
  """
  def hello do
    :world
  end
end
```

I don't know if this is of much help but wanted to provide at least another example of how this bug can be reproduced so that if you ever decide to take a look into it you can also experiment this case :)

**Comment by RobertDober** [comment]
@joaofcosta thank you for that detailed report, will turn out helpful for sure

**Comment by wojtekmach** [comment]
Btw, remember code blocks should be indented with 4 spaces, this way they will be nicely printed in ExDoc, IEx, etc, as well as they won’t trigger the bug :)

**Comment by RobertDober** [comment]
Pushing into 1.4.6 as #342 is more serious and no easy workaround exists.
