### ISSUE TITLE
Upgrading 1.4.4 -> 1.4.5 introduces Dialyzer error

### ISSUE THREAD

**Issue by doughsay** [pragdave/earmark#347]
I cloned earmark to see if I could quickly get to the bottom of it, but it's a bit over my head.

Earmark itself produces a handful of dialyzer errors, but most of them don't seem to have an effect on a consuming application.  But one of them does now:

```
:0:unknown_function
Function Earmark.HtmlRenderer.render_code/1 does not exist.
```

Not sure why this is the case, as the function does seem to exist...

**Comment by RobertDober** [comment]
sorry about that, I do not use dialyzer yet but I'll try to get rid of this

**Comment by RobertDober** [comment]
Actually I have seen this in 1.4.4 too, I am afraid I cannot fix all Dialyzer errors in this release but I got rid of two obvious ones.

HTH

**Comment by doughsay** [comment]
I can easily ignore errors, so it doesn't bother me much; just wanted to raise the issue in case nobody was aware :smiley:
