### ISSUE TITLE
Code blocks near list items are interpreted as text

### ISSUE THREAD

**Issue by wojtekmach** [pragdave/earmark#349]
```
    code = """
    * List item

      Text

        * List item

      Text

          https://mydomain.org/user_or_team/repo_name/blob/master/%{path}#L%{line}

    """

    IO.inspect Earmark.as_ast(code)
```

results in:

```
     ** (ArgumentError) malformed URI "https://mydomain.org/user_or_team/repo_name/blob/master/%"
     code: IO.inspect Earmark.as_ast(code)
     stacktrace:
       (elixir 1.10.2) lib/uri.ex:344: URI.decode/1
       (earmark 1.4.5) lib/earmark/helpers/ast_helpers.ex:58: Earmark.Helpers.AstHelpers.render_link/2
       (earmark 1.4.5) lib/earmark/helpers/pure_link_helpers.ex:25: Earmark.Helpers.PureLinkHelpers.determine_ending_parens_by_count/3
       (earmark 1.4.5) lib/earmark/ast/inline.ex:100: Earmark.Ast.Inline.converter_for_pure_link/1
```

An easy workaround in the meantime is to change:

```
    https://mydomain.org/user_or_team/repo_name/blob/master/%{path}#L%{line}
```

to:

    ```
    https://mydomain.org/user_or_team/repo_name/blob/master/%{path}#L%{line}
    ```

P.S. I found this when running `cd /path/to/ex_doc && mix build` on Earmark 1.4.5, I'll use the workaround on ExDoc master soon.

**Comment by RobertDober** [comment]
Thank you for this, I shall be able to allocate some, much needed, time for Earmark soon

**Comment by RobertDober** [comment]
Oh but @josevalim already fixed this, just great! \o/

**Comment by RobertDober** [comment]
However not

**Comment by RobertDober** [comment]
This works:

```elixir
 code = "<https://mydomain.org/user_or_team/repo_name/blob/master/%{path}#L%{line}>"
"<https://mydomain.org/user_or_team/repo_name/blob/master/%{path}#L%{line}>"
iex(11)> Earmark.as_ast(code)                                                                
{:ok,
 [
   {"p", [],
    [
      {"a",
       [
         {"href",
          "https://mydomain.org/user_or_team/repo_name/blob/master/%{path}#L%{line}"}
       ],
       ["https://mydomain.org/user_or_team/repo_name/blob/master/%{path}#L%{line}"]}
    ]}
 ], []}
```

GFM compatibility is quite a challange

**Comment by RobertDober** [comment]
@wojtekmach I am not sure about the code block as text observation though, seems to me that no text is indented enough to be a code block, if I am wrong, sorry these GFM list indention rules have costed me my sanity oftentimes...

**Comment by josevalim** [comment]
> seems to me that no text is indented enough to be a code block

Yup, this is always extremely confusing to me too.

**Comment by josevalim** [comment]
Although if we try out the example @wojtekmach gave on GitHub, it does highlight the URL as code. :)

**Comment by RobertDober** [comment]
just checked with Babelmark

 https://babelmark.github.io/?text=*+List+item%0A%0A++Text%0A%0A++++*+List+item%0A%0A++Text%0A%0A++++++https%3A%2F%2Fmydomain.org%2Fuser_or_team%2Frepo_name%2Fblob%2Fmaster%2F%25%7Bpath%7D%23L%25%7Bline%7D%0A 

and indeed this should be code, so we got 2 bugs here:

I'll open a different issue for the cut URL,  guess the babelmark URL is a good test case BTW ;)

And will treat the bug posted by OP as such here.

**Comment by RobertDober** [comment]
I gotta study this one once more --> 1.4.7/1.5

**Comment by RobertDober** [comment]
shall be fixed with https://github.com/RobertDober/earmark_parser/issues/9
