### ISSUE TITLE
v1.4.8 `function EarmarkParser.as_ast/2 is undefined (module EarmarkParser is not available)`

### ISSUE THREAD

**Issue by samm81** [pragdave/earmark#375]
I'm getting a rather strange error. I upgraded `:earmark` from v1.4.5 ⇒ v1.4.8 , and am now getting an error with `Earmark.as_html!/2` *only in a release*. It works fine with `mix phx.server`, but in the release I get this error:

```
    ** (UndefinedFunctionError) function EarmarkParser.as_ast/2 is undefined (module EarmarkParser is not available)
        EarmarkParser.as_ast("some mardown", [breaks: false, code_class_prefix: nil, do_smartypants: nil, file: "<no file>", footnote_offset: 1, footnotes: false, gfm: true, gfm_tables: false, line: 1, mapper: &Earmark.pmap/2, mapper_with_timeout: &Earmark.pmap/3, messages: [], pedantic: false, pure_links: true, renderer: Earmark.HtmlRenderer, smartypants: true, timeout: nil])
        (earmark 1.4.8) lib/earmark.ex:423: Earmark.as_html/2
        (earmark 1.4.8) lib/earmark.ex:460: Earmark.as_html!/2
        (my_app 0.1.0) lib/my_app_web/views/my_view.ex:117: MyAppWeb.MyView.markdown_to_html/1
```

I'm kinda flummoxed. I'll look into it more, but wanted to post this here first.

**Comment by RobertDober** [comment]
:fearful: thank you for reporting this

**Comment by RobertDober** [comment]
I have a hunch though, seems I _forgot_ to put `EarmarkParser` into applications (needs to be test covered).

Would be great if you could test (or tell me how to test, I'll gladly do my work :wink: ) with the current master from github, I could do a release any time

**Comment by juulSme** [comment]
I have the same issue with 1.4.8 and I can confirm that adding `:earmark_parser` to extra applications in mix.exs fixes the issue.

**Comment by RobertDober** [comment]
Thx a lot @juulSme hotfix release's coming up

**Comment by juulSme** [comment]
np, keep up the good work!

**Comment by RobertDober** [comment]
very kind of you  but I lack so much knowledge thankfully the community is very helpful

**Comment by samm81** [comment]
wow, thanks for figuring this out and patching it up so fast :+1: !

**Comment by RobertDober** [comment]
> wow, thanks for figuring this out and patching it up so fast  !

Ty but all credit goes to @eksperimental and @juulSme
