### ISSUE TITLE
Spacing is removed between link and elements 

### ISSUE THREAD

**Issue by sb8244** [pragdave/earmark#382]
When I pass a string like `*Test* https://www.google.com` into the `as_html` function, I get back a result that doesn't have spacing:

Here is an example with many spaces added:

```
iex(12)> Earmark.as_html!("**Test**          https://www.google.com")
"<p>\n<strong>Test</strong><a href=\"https://www.google.com\">https://www.google.com</a></p>\n"
```

If the first element is just simple text, it includes the spaces:

```
iex(13)> Earmark.as_html!("Test          https://www.google.com")    
"<p>\nTest          <a href=\"https://www.google.com\">https://www.google.com</a></p>\n"
```

This might be expected, but thought I'd report it in case it's a bug.

**Comment by RobertDober** [comment]
Thank you for the report it is indeed an error, but not in Earmark but in EarmarkParser, I'll transfer the ticket.

**Comment by RobertDober** [comment]
fixed on EarmarkParser side
