### ISSUE TITLE
Smartypants curly quotes are in inline code.

### ISSUE THREAD

**Issue by dbernheisel** [pragdave/earmark#383]
Using these versions:

```elixir
  "earmark": {:hex, :earmark, "1.4.10", "bddce5e8ea37712a5bfb01541be8ba57d3b171d3fa4f80a0be9bcf1db417bcaf", [:mix], [{:earmark_parser, ">= 1.4.10", [hex: :earmark_parser, repo: "hexpm", optional: false]}], "hexpm", "12dbfa80810478e521d3ffb941ad9fbfcbbd7debe94e1341b4c4a1b2411c1c27"},
  "earmark_parser": {:hex, :earmark_parser, "1.4.10", "6603d7a603b9c18d3d20db69921527f82ef09990885ed7525003c7fe7dc86c56", [:mix], [], "hexpm", "8e2d5370b732385db2c9b22215c3f59c84ac7dda7ed7e544d7c459496ae519c0"},
```

and running this:

````markdown
"Hello"

Inline Code: `IO.puts "Hello"`

Block Code: 
```
IO.puts "Hello"
```
````

```elixir
iex> Earmark.as_html!("\"Hello\"\n\nInline Code: `IO.puts \"Hello\"`\n\nBlock Code: \n```\nIO.puts \"Hello\"\n```", %Earmark.Options{smartypants: true})
"<p>\n“Hello”</p>\n<p>\nInline Code: <code class=\"inline\">IO.puts “Hello”</code></p>\n<p>\nBlock Code: </p>\n<pre><code>IO.puts &quot;Hello&quot;</code></pre>\n"
```
Notice the inline code still has smartypants curly quotes: `“Hello”`, which is incorrect.

As a comparison:

markdown-it:
![image](https://user-images.githubusercontent.com/643967/90142278-2cf82600-dd4a-11ea-93b9-1b516ca5f017.png)

[The smartypants spec (I guess this is the spec?)](https://daringfireball.net/projects/smartypants/)

> SmartyPants does not modify characters within `<pre>`, `<code>`, `<kbd>`, or `<script>` tag blocks. 
> Typically, these tags are used to display text where smart quotes and other “smart punctuation” would not be appropriate, such as source code or example markup.

Somewhat related: https://github.com/pragdave/earmark/issues/210#issuecomment-447683907

**Comment by dbernheisel** [comment]
Seems to be introduced in [earmark 1.4.7](https://github.com/pragdave/earmark/compare/v1.4.6..v1.4.7)

**Comment by RobertDober** [comment]
Nice catch, thank you!
