### ISSUE TITLE
Empty lines are removed in code blocks in a list element

### ISSUE THREAD

**Issue by tidusIO** [pragdave/earmark#385]
If I have the following markdown, we are loosing the empty lines:

`1. Create the file `src/screens/ColoredButtonsScreen.tsx` (you might have to create the new folders).
2. Inside it create the backbone of a basic React Functional Component, in fact:

	```tsx
	import React from "react";
	import { Text, View } from "react-native";
  
	const ColoredButtonsScreen = () => {
      return (
          <View>
            <Text>Hello World</Text>
          </View>
      );
	}

	export default ColoredButtonsScreen;
	```

Here are both rendered HTMLs:

`<code class="tsx hljs javascript"> <span class="hljs-keyword"><span class="hljs-keyword">import</span></span> React <span class="hljs-keyword"><span class="hljs-keyword">from</span></span> <span class="hljs-string"><span class="hljs-string">"react"</span></span>;
 <span class="hljs-keyword"><span class="hljs-keyword">import</span></span> { Text, View } <span class="hljs-keyword"><span class="hljs-keyword">from</span></span> <span class="hljs-string"><span class="hljs-string">"react-native"</span></span>;
 <span class="hljs-keyword"><span class="hljs-keyword">const</span></span> ColoredButtonsScreen = <span class="hljs-function"><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">()</span></span></span>.....</code>`

`<code class="tsx hljs javascript"><span class="hljs-keyword"><span class="hljs-keyword">import</span></span> React <span class="hljs-keyword"><span class="hljs-keyword">from</span></span> <span class="hljs-string"><span class="hljs-string">"react"</span></span>;
<span class="hljs-keyword"><span class="hljs-keyword">import</span></span> { Text, View } <span class="hljs-keyword"><span class="hljs-keyword">from</span></span> <span class="hljs-string"><span class="hljs-string">"react-native"</span></span>;

<span class="hljs-keyword"><span class="hljs-keyword">const</span></span> ColoredButtonsScreen = <span class="hljs-function"><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">()</span></span></span><span class="hljs-function"> =&gt;</span></span> {
.....</code>`

**Comment by RobertDober** [comment]
That is because you do not close your code block properly **four** ` instead of 3

However the error message is missing so I will open a different ticket for the missing error message and in EarmarkParser

Please close this issue if you are happy with this 

```elixir
iex(4)> lines1 = """                   
...(4)> ```tsx
...(4)> import React from "react";
...(4)> import { Text, View } from "react-native";
...(4)> 
...(4)> const ColoredButtonsScreen = () => {
...(4)>   return (
...(4)>       <View>
...(4)>         <Text>Hello World</Text>
...(4)>       </View>
...(4)>   );
...(4)> }
...(4)> 
...(4)> export default ColoredButtonsScreen;
...(4)> ``` 
...(4)> """
"```tsx\nimport React from \"react\";\nimport { Text, View } from \"react-native\";\n\nconst ColoredButtonsScreen = () => {\n  return (\n      <View>\n        <Text>Hello World</Text>\n      </View>\n  );\n}\n\nexport default ColoredButtonsScreen;\n```\n"
iex(5)> IO.puts(Earmark.as_html! lines1)          
<pre><code class="tsx">import React from &quot;react&quot;;
import { Text, View } from &quot;react-native&quot;;

const ColoredButtonsScreen = () =&gt; {
  return (
      &lt;View&gt;
        &lt;Text&gt;Hello World&lt;/Text&gt;
      &lt;/View&gt;
  );
}

export default ColoredButtonsScreen;</code></pre>
```

**Comment by RobertDober** [comment]
https://github.com/RobertDober/earmark_parser/issues/23

**Comment by saschanuissl** [comment]
These 4 backticks are only here in my github example. I had some trouble here to put the list and the code block in another code block.

<img width="797" alt="Screenshot 2020-08-20 at 03 14 59" src="https://user-images.githubusercontent.com/5259847/90709103-57d70280-e293-11ea-8702-9ea6a58f131e.png">

Should be more clear with my screenshot.

<img width="1079" alt="Screenshot 2020-08-20 at 03 15 46" src="https://user-images.githubusercontent.com/5259847/90709149-776e2b00-e293-11ea-9f91-24baecfc9d44.png">

**Comment by RobertDober** [comment]
Oh that's easy just indent the code with the backicks by at least 4 characters as I did below

    ```elixir
        IO.puts(42)
    ```

and then please tell me what you expect as a result.

Thank you

**Comment by saschanuissl** [comment]
**Code**
<img width="424" alt="Screenshot 2020-08-20 at 12 13 44" src="https://user-images.githubusercontent.com/5259847/90763431-99d96600-e2de-11ea-9145-25da9d6c6b56.png">

**Result**
<img width="437" alt="Screenshot 2020-08-20 at 12 13 19" src="https://user-images.githubusercontent.com/5259847/90763406-8b8b4a00-e2de-11ea-8cc6-9776a207f0e6.png">

**Expected**
<img width="490" alt="Screenshot 2020-08-20 at 12 14 51" src="https://user-images.githubusercontent.com/5259847/90763527-c2616000-e2de-11ea-817a-c355c6633df7.png">

_____________________

Example here in Github. It renders it correctly

1. Markdown inside list element

    ```elixir
        IO.puts("first line")

        IO.puts("second line with whitespace above")
    ```
    
Markdown without list element

```elixir
    IO.puts("first line")

    IO.puts("second line with whitespace above")
```

Thanks for your effort 👍

**Comment by RobertDober** [comment]
Ok got it!

Had to edit your comment to get to the erroneous input though

**Comment by RobertDober** [comment]
This is definitely related to https://github.com/RobertDober/earmark_parser/issues/9 and will be fixed there

**Comment by RobertDober** [comment]
should be fixed
