### ISSUE TITLE
Unescaped < and inline html

### ISSUE THREAD

**Issue by RobertDober** [pragdave/earmark#40]
I am not sure if this is a bug indeed.

Anyway, without inline html `<` is perfectly transformed

```elixir
iex(4)> Earmark.to_html " a<x"
"<p> a&lt;x</p>\n"
```

That changes if the line contains html

```elixir
iex(6)> Earmark.to_html "x<max<br/>"
"<p>x<max<br/></p>\n"
```

An indication that it is a bug is maybe the following transformation, note the additional space

```elixir
Earmark.to_html "x< max<br/>"
"<p>x&lt; max<br/></p>\n"
```

Any opinions?

**Comment by pragdave** [comment]
I’m guessing it is interpreting it as the self-closing tag

<max<br/>

Perhaps the regexp that matches tags should have a [^<] in it?
​

**Comment by RobertDober** [comment]
Logical conclusion, Dave, it is also interpreted as an opening tag in this context

```elixir
iex(1)> Earmark.to_html "<a<p>hello</p>"
Failed to find closing <a>
"<a<p>hello</p>\n"
iex(2)> Earmark.to_html "<a <p>hello</p>"
Failed to find closing <a>
"<a <p>hello</p>\n"     
```

will look at it as soon as possible.
