### ISSUE TITLE
HTML gets stripped

### ISSUE THREAD

**Issue by tmjoen** [pragdave/earmark#400]
Hello!

There looks to be a slight problem in version 1.4.13:
```elixir
iex(1)> Earmark.as_html!("<h3>A header here</h3><p>Followed by some text</p>")
"<h3>\n  A header here</h3>\n"
```

Everything after the first tag seems to get stripped.

After reverting to 1.4.4 (the previous version I used):

```elixir
iex(1)> Earmark.as_html!("<h3>A header here</h3><p>Followed by some text</p><p>and some more</p>")
"<h3>A header here</h3><p>Followed by some text</p><p>and some more</p>"
```

**Comment by RobertDober** [comment]
This is expected and documented behavior.
https://github.com/pragdave/earmark#limitations

That said 1.5 aims to parse full HTML.
