### ISSUE TITLE
map_ast cannot change content

### ISSUE THREAD

**Issue by RobertDober** [pragdave/earmark#421]

**Comment by cheerfulstoic** [comment]
Did you end up making this work?  I can't seem to transform content with `map_ast` either

**Comment by RobertDober** [comment]
I guess so what's your problem? 

However I will probably not have time to work on this for weeks, sorry.

**Comment by cheerfulstoic** [comment]
Not a big deal 😄 .  I was trying to take some markdown files that I had and use `Code.format_string!/2` to format Elixir code blocks.
