### ISSUE TITLE
Entities and inline HTML

### ISSUE THREAD

**Issue by tomconroy** [pragdave/earmark#449]
There is a regression since 9127d91c0745a28d87bd61dd4484856e98d88cd7. I compare output to the previous commit below (from 32b6ded)

[HTML entities should not be escaped within markdown blocks](https://daringfireball.net/projects/markdown/syntax#autoescape)

```elixir
Earmark.as_html("&nbsp;")
{:ok, "<p>\n&amp;nbsp;</p>\n", []}

# expect 
"<p>&nbsp;</p>\n"
```

Note that ampersands *should* be escaped if they're not part of an HTML entity as they do currently.

```elixir
Earmark.as_html(~s(Foo & bar &amp; baz))

# expect
"<p>Foo &amp; bar &amp; baz</p>\n"
```

Similarly, [inline HTML should be allowed](https://daringfireball.net/projects/markdown/syntax#html)

```elixir
Earmark.as_html(~s(Foo <a href="/bar">*baz*</a> <img src="foo.jpg">))
{:ok,
 "<p>\nFoo &lt;a href=”/bar”&gt;<em>baz</em>&lt;/a&gt; &lt;img src=”foo.jpg”&gt;</p>\n",
 []}

# expect
"<p>Foo <a href=\"/bar\"><em>baz</em></a> <img src=\"foo.jpg\"></p>\n"
```

These should be allowed in other markdown blocks like headers too.

```elixir
Earmark.as_html(~s(# Foo <a href="/bar">*baz*</a>))                    
{:ok, "<h1>\nFoo &lt;a href=”/bar”&gt;<em>baz</em>&lt;/a&gt;</h1>\n", []}

# expect
{:ok, "<h1>Foo <a href=\"/bar\"><em>baz</em></a></h1>\n", []}
```

**Comment by RobertDober** [comment]
@tomconroy thank you for this report, unfortunately I cannot give you an ETA on this :(

**Comment by RobertDober** [comment]
>[HTML entities should not be escaped within markdown blocks](https://daringfireball.net/projects/markdown/syntax#autoescape)

seems the default options got mixed up

```elixir
iex(1)> Earmark.as_html("&nbsp;")
{:ok, "<p>\n&amp;nbsp;</p>\n", []}
iex(2)> Earmark.as_html("&nbsp;", escape: false)
{:ok, "<p>\n&nbsp;</p>\n", []}
```
sorry about that, but now I wonder if it makes sense to _repair_ this, given for how long this switch had been introduced and my conclusion is: sorry, no

> Similarly, [inline HTML should be allowed](https://daringfireball.net/projects/markdown/syntax#html)
No it is explicitly not allowed in 1.4 this is a design choice made from the beginning, it should be _fixed_ in 1.5 if I ever will find the time for 1.5 :(
