### ISSUE TITLE
🐞 BUG: 1.5.0-pre1 outputting list of links

### ISSUE THREAD

**Issue by jzwood** [pragdave/earmark#458]
## earmark version
`{:earmark, "1.5.0-pre1"}`

## input markdown
```
- <a href="https://www.mozilla.com">Mozilla</a>
- <a href="/mozilla.com">Mozilla</a>
```

## expected output when escape=false
```
<li> <a href="https://www.mozilla.com">Mozilla</a> </li>
<li> <a href="/mozilla.com">Mozilla</a> </li>
```

## actual output
```
<li><a href="”<a">https://www.mozilla.com”</a>&gt;Mozilla</li>
<li><a href="/mozilla.com">Mozilla</a></li>
```

## Description
![Screen Shot 2023-01-17 at 5 37 18 PM](https://user-images.githubusercontent.com/13749324/213027646-abfc3656-0e1d-4458-bd31-8fd262fad499.png)

As you can see, the second item outputs correctly but the first one does not.

**Comment by RobertDober** [comment]
Thank you for reporting this, but I have to admit that 1.5 is quite dead for some while, are you using it, or just playing around with it.

If you use it maybe you can go with the 1.4 branch, if not please tell me what's missing there is just no way I can work on 1.5 in the near future.

Sorry for the inconvenience

**Comment by RobertDober** [comment]
However this behavior is documented, one html tag per line in 1.4 I do not think I can backport this from 1.5 to 1.4

**Comment by jzwood** [comment]
Just messing around with it. It breaks in exactly the same way for version 1.4.34

**Comment by RobertDober** [comment]
@jzwood 
that this just does not work in 1.4
```
<li> <a href="https://www.mozilla.com">Mozilla</a> </li>
```

but definitely shall in 1.5
