### ISSUE TITLE
Does Earmark have any support for entering latex math into markdown

### ISSUE THREAD

**Issue by CharlesIrvineKC** [pragdave/earmark#461]
In my LiveView app, I am displaying markdown text as HTML using Earmark. I would like to now support entering math symbols, for example, an equation, etc, into my markdown text, and getting that displayed properly in the Earmark translation to HTML. I had hoped that there was support for this but I’m not finding any. Does Earmark have any support for this?

**Comment by RobertDober** [comment]
I am afraid this is not on the radar.

**Comment by CharlesIrvineKC** [comment]
Darn. Well, maybe I'll switch over to something like Quill. Thanks for letting me know.

**Comment by CharlesIrvineKC** [comment]
Regarding this issue, I did find what seems like a good solution. Latex math symbols are nice rendered using [MathJax](https://www.mathjax.org/). Instructions are [here](https://www.mathjax.org/#gettingstarted). For your Earmark container element, you will need to specify **phx-update="ignore"**.

**Comment by RobertDober** [comment]
I do not know if a full fledged HTML parser will solve this issue, but I guess it might, this is on the radar for 1.5 and I will work on it in my free time. (Target v1.5)

However ETA ???, I dunno, if I win the lottery, 2 weeks 😅

**Comment by RobertDober** [comment]
BTW what does not work right now? If you put all tags in one line

```
 λ cat tmp/math.md                                                                                                                                                   [8:16:41]
# Some Math
<p>
 When \(a \ne 0\), there are two solutions to \(ax^2 + bx + c = 0\) and they are
  \[x = {-b \pm \sqrt{b^2-4ac} \over 2a}.\]
</p>

╭─>robert@aude ~/gh/elixir/earmark                                                                                                            ❰1.14➤25.0.4❱ [±ed1642d ●]
╰─> λ earmark tmp/math.md                                                                                                                                               [8:16:51]
<h1>Some Math</h1>
<p>
 When \(a \ne 0\), there are two solutions to \(ax^2 + bx + c = 0\) and they are
  \[x = {-b \pm \sqrt{b^2-4ac} \over 2a}.\]
</p>
```

**Comment by CharlesIrvineKC** [comment]
@RobertDober Don't know if you saw my previous post, but I do have what seems like a nice solution. Latex math symbols are nicely rendered using [MathJax](https://www.mathjax.org/). Instructions are [here](https://www.mathjax.org/#gettingstarted). This is the same library that GitHub uses to render math symbols in markdown files. https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions

For my template container element, I need to specify phx-update="ignore". 



```
<p>$$\left( \sum_{k=1}^n a_k b_k \right)^2 \leq \left( \sum_{k=1}^n a_k^2 \right) \left( \sum_{k=1}^n b_k^2 \right)$$</p>
```

renders as this:

![Untitled](https://github.com/pragdave/earmark/assets/657002/9f855a29-96a1-4031-ad68-993bde2b489d)

**Comment by RobertDober** [comment]
Great, yes I was not concerned about the template as you have full control but only if Earmark might unescape characters or other stuff which might cause problems.

Happy it does not.

Thanx for the update.

**Comment by RobertDober** [comment]
And thanx too for the example which is a formula of a French mathematicien IIRC 🤣
