### ISSUE TITLE
em-dash cannot be escaped

### ISSUE THREAD

**Issue by tusooa** [pragdave/earmark#464]
downstream: https://git.pleroma.social/pleroma/pleroma/-/issues/2810

When `smartypants` is on, `\-\-` is converted to `–`. This behaviour sounds problematic, because it is not two **consecutive** dashes.

```
iex(3)> Earmark.as_html("hey @yyy@xn\\-\\-i2raa\\.com")
{:ok, "<p>\nhey @yyy@xn–i2raa.com</p>\n", []}
```

This causes problems for our workflow, because it represents a domain name and thus should not be converted.

**Comment by RobertDober** [comment]
Ty for this report, unfortunately the smarty pants option is deprecated, which version of Earmark do you use?

**Comment by tusooa** [comment]
earmark 1.4.22 and earmark_parser 1.4.32

**Comment by RobertDober** [comment]
I see what you mean but why should we not create a dash? 

In links we do not
```
Earmark.as_html("hey @<yyy@xn\\-\\-i2raa\\.com>")
{:ok,
 "<p>\nhey @<a href=\"mailto:yyy@xn%5C-%5C-i2raa%5C.com\">yyy@xn\\-\\-i2raa\\.com</a></p>\n",
 []}
```
but switching smarty_pants off is broken, someone will hopefully fix this.

**Comment by RobertDober** [comment]
> And even if it is handled as a link it is still buggy: the text of the link should also not have the em-dash -- it should have the double ascii dashes instead.
Matter of taste I would say, but if your desired behavior would solve your problem I would defenitely consider accepting a PR.

That said, is  using `smartypants: false` not fixing your issue?

**Comment by tusooa** [comment]
Switching off smartypants fixes the issue, but as Pleroma is a piece of software that advocates for customizability, it is apparently better if this option is customizable without breaking anything.
