### ISSUE TITLE
Failed to find closing tag when it's trailing after text in another line

### ISSUE THREAD

**Issue by lobo-tuerto** [pragdave/earmark#465]
Hello,

I have tried parsing this Markdown:

```md
# Some title

<small>Some text  
**Hello**  
From some date – Current</small>
```

Which is loaded by Elixir as:

```elixir
"# Some title\n\n<small>Some text  \n**Hello**  \nFrom some date – Current</small>\n"
```

But, when passed to Earmark it complains with:

```elixir
{:error,
 "<h1>\nSome title</h1>\n<small>\n  Some text    **Hello**  \nFrom some date – Current</small></small>\n",
 [{:warning, 3, "Failed to find closing <small>"}]}
```

I'm migrating this code from an old JavaScript app into Elixir.  
Used **markdown-it** to parse the file back there with no issues.

The problem goes away if I pull the closing tag to the next line, but wonder why that is needed in the first place. :thinking: 

Is this expected?

**Comment by RobertDober** [comment]
This is expected behavior you need to close tags in a new line https://github.com/RobertDober/earmark_parser#html-blocks
I guess it might not be clear from the docs that the parsing is documented in the EarmarkParser

PRs welcome ;)

**Comment by RobertDober** [comment]
BTW if I ever get the time to work on 1.5 HTML will be parsed recursevily but  that is a big **if**

**Comment by lobo-tuerto** [comment]
Fair enough, thanks for explanation. :)
