### ISSUE TITLE
from_file! ignores the options if not a .eex file is passed

### ISSUE THREAD

**Issue by bandesz** [pragdave/earmark#466]
## What

I tried to disable `smartypants` in `from_file!`, but it had no affect:
```elixir
Earmark.from_file!("README.md"), smartypants: false)
```

After looking through the code I found eventually `include`:
```elixir
def include(filename, options \\ []) do
  options_ =
    options
    |> Options.relative_filename(filename)
  case Path.extname(filename) do
    ".eex" -> EEx.eval_file(options_.file, include: &include(&1, options_))
    _      -> SysInterface.readlines(options_.file) |> Enum.to_list
  end
end
```

For files other than "*.eex" the options are just ignored.

**Comment by RobertDober** [comment]
Thank you for your report, I am on vacation right now and might not be able to look at this in the near future though.

**Comment by RobertDober** [comment]
I took a look at it and I do not see a problem. 
Recofgnized options are all passed to `EarmarkParser` (for `.md` files too) however many legal options do not seem to be recognized which I will fix soon hopefully.

Please be aware that `smartypants` are deprecated

What you have seen in the code is just that `EEx` needs the options too :)

**Comment by RobertDober** [comment]
Still investigating
