### ISSUE TITLE
ast back to markdown

### ISSUE THREAD

**Issue by tiagodavi** [pragdave/earmark#469]
Hi Folks, thank you for the great library.

Is there a way I can change the AST and print the markdown (not the html) back with the updated AST?

Thank you

**Comment by RobertDober** [comment]
First of all thank you for the praise ;), however we would need some "folks" to maintain the library as it is orphaned right now.

Secondly that is an interesting question. 
You cannot create the _original_ markdown, because there are different link formats, to name just one parsing operation that is not reversible.

You can most definitely create markdown from the AST that would parse to the same AST again.

Out of couriosity, what is your use case of that feature?
Now it would be possible to instruct

**Comment by tiagodavi** [comment]
Thank you Robert.

I would like to create the same feature we have here in GitHub where the user can write markdown and preview it in html, but at the same time the user can also edit directly the preview , for example by checking checkboxes with a list of tasks and it will edit and save the preview and of course it will check the markdown as well so if the user had [] task it will have [x] task . Does that make sense ?

**Comment by tiagodavi** [comment]
I have created the real time markdown editor with preview by editing the ast, but I am still thinking about the best way to create something like .as_markdown feature similar the as_html one.

**Comment by RobertDober** [comment]
> I would like to create the same feature we have here in GitHub where the user can write markdown and preview it in html, but at the same time the user can also edit directly the preview , for example by checking checkboxes with a list of tasks and it will edit and save the preview and of course it will check the markdown as well so if the user has [] task it will have [x] task . Does that make sense ?

Beautiful, you make my decision to stop maintaining Earmark even harder. 

I am just wondering, in that case, is my statement that you can definitely create markdown from the AST that will create the same AST again, not enough.

It is a little bit like running a linter, your code will change but not its semantics, right?

**Comment by tiagodavi** [comment]
When someone changes the html it changes the ast at the same time, so if I can use this ast to update the markdown it will sove the problem, but it's not that easy.. 

Example:

Markdown: - `[ ] Task`
My HTML parsers the ast to checkboxes: `<input type checkbox /> Task` 
Someone has checked in real-time it will update the ast: `<input type checkbox checked /> Task `
now I want to update the markdown as well: `[x] Task`. <<< this is what is missing currently in my implementation.
Because of this I thought to create a function as_markdown (it replaces checkbox with markdown list)

https://github.com/tiagodavi/ex_markdown_parser

**Comment by RobertDober** [comment]
I will not have the time to implement task lists. If this is all you need you should probably open a new issue to ask for it, I had turned it down when Earmark and EarmarkParser were connected, now that they are free I am not opposed to it, we just need to find someone who implements it 😓 
If this is all, maybe you can close this?

I liked our discussion, but, alas, I will probably not have time in weeks now to continue.

**Comment by tiagodavi** [comment]
Yeah I will try to send a pr with this feature because I think it makes sense to turn lists into checkboxes right? Thank you
