### ISSUE TITLE
Duplicated modules using earmark and earmark_parser

### ISSUE THREAD

**Issue by EasterPeanut** [pragdave/earmark#473]
I get this error in my release when using both earmark 1.4.45 and earmark_parser 1.4.36:
 
```
** (Mix) Duplicated modules: 
        string_lexer specified in earmark and earmark_parser
	link_text_parser specified in earmark and earmark_parser
	link_text_lexer specified in earmark and earmark_parser
```

**Comment by RobertDober** [comment]
Thank you EasterPeanut, you put the finger where it hurts, actually the fix should not be too difficult, I need to change the names of the lexers in `Earmark` however there are two problems here

1. I am not planning to maintain `Earmark` any longer, but I might be able to squeeze a "fix" (see below) in this WE (but no promises)
2. @josevalim, should this even happen? Looks like a bug to me that the leex and yex files leak from the package? @EasterPeanut could you please provide us with the complete setup of your application?

**Comment by RobertDober** [comment]
Note to self:
Pseudo namespace lexer and yecc in `Earmark` and `EarmarkParser`

**Comment by josevalim** [comment]
@RobertDober I can submit PRs for both if you want. :)

**Comment by lifeofdan** [comment]
Isn't this fixed with the merge of https://github.com/pragdave/earmark/pull/474 ? If it is, this could be marked as closed.

**Comment by RobertDober** [comment]
@lifeofdan Thank you for the reminder
