### ISSUE TITLE
I'd like to maintain earmark

### ISSUE THREAD

**Issue by amit-chaudhari1** [pragdave/earmark#477]
I'd like to pitch myself for maintaining earmark.

**Comment by amit-chaudhari1** [comment]
Following the ideas mentioned by @RobertDober [here](https://elixirforum.com/t/earmark-is-looking-for-a-maintainer/58380/6?u=amyth) and [here](https://github.com/RobertDober/earmark_parser/issues/133#issuecomment-1722407140)

There some issues that appear to be pre-split. I think we'll need to revisit and decide on if they are still earmark issue or earmark-parser issue.

Aside from triage of issues, I'd like to focus on 
1. [Decoupling earmark from earparser](https://github.com/RobertDober/earmark_parser/issues/133#issuecomment-1722407140) This will involve working in collaboration with contributors from earmark-parser and ex-doc, I'll be working towards a release where a new version release for earmark does not concern folks using earmark-parser. We'll be trying to isolate the layer of concerns handled by both these libraries.
2. Make progress towards making earmark mainly to be a general-purpose MD → HTML renderer that may or may not use earmark-parser under the hood. I really like how [they put it in words](https://elixirforum.com/t/earmark-is-looking-for-a-maintainer/58380/5)
3. Open to ideas around performance improvements, size reductions and other optimizations, but I'll set it a side as a long term goal to be working towards for now.

I'll also like to propose introduction to milestone's and other project management chores to improve clarity and communication about what we are working towards currently.

Please treat this as a discussion for things that you'd like the maintainers to be focusing on.

**Comment by RobertDober** [comment]
I am completely fine with this

@pragdave if this is fine with you can you please grant all necessary rights to @amit-chaudhari1 ?

Thank you all (not forgetting @bradhanks

**Comment by RobertDober** [comment]
@amit-chaudhari1 can you please confirm that you have committement rights?
I do not know about hex access, but for now I am happy to do the releases if you do not have access.

**Comment by bradhanks** [comment]
> @amit-chaudhari1 can you please confirm that you have committement rights? I do not know about hex access, but for now I am happy to do the releases if you do not have access.

Having the chance to work with someone more experienced on board is a good opportunity for me. I could be pretty good at doing stuff like adding documentation, type specifications, formatting, refactoring, etc.

**Comment by RobertDober** [comment]
Happy to pass the puck on ;) I'll help as much as I can, if needed.
