### ISSUE TITLE
Announcement for change of maintainer

### ISSUE THREAD

**Issue by RobertDober** [pragdave/earmark#480]
@amit-chaudhari1 would you like me to make an announcement that you have taken over as a maintainer in the Earmark Thread of the Elixir Forum https://elixirforum.com/t/earmark-is-looking-for-a-maintainer/58380/6?

**Comment by amit-chaudhari1** [comment]
I'd appreciate that. Thank you

**Comment by RobertDober** [comment]
Done: https://elixirforum.com/t/earmark-is-looking-for-a-maintainer/58380/7
