### ISSUE TITLE
[Version 0.2.0] ```elixir ```` and [MIT](LICENSE.md) external file support broken in README.md

### ISSUE THREAD

**Issue by seantanly** [pragdave/earmark#57]
Thanks for constantly improving earmark. 

The above is still working in 0.1.19 but is broken in 0.2.0.

```elixir ``` isn't being recognise as a code block and link parsing support for external file such as [MIT](LICENSE.md) isn't working anymore.

**Comment by RobertDober** [comment]
I am not sure what you mean with the above.

```
```elixir ```` and [MIT](LICENSE.md)
```
?

Can you please indicate the input and the expected output.

Thx

**Comment by seantanly** [comment]
Examples below are taken from what is generated from 0.1.19 output, 

```elixir
iex> a = 1
```
should transform to
```
<pre>
<code class="elixir hljs">
<span class="hljs-constant">a</span>
=
<span class="hljs-number">1</span>
</code>
</pre>
```

```
[MIT](LICENSE.md) 
```
should transform to 
```
<a href="LICENSE.md">MIT License</a>
```

In version 0.2.0, they are being parsed as text with no transformation.

**Comment by seantanly** [comment]
I forgot to mention this is in the context of generating docs using `ex_docs` while relying on earmark for markdown parsing.

**Comment by RobertDober** [comment]
I get seemingly correct results

```elixir
iex(8)> :application.get_key(:earmark, :vsn)   
{:ok, '0.2.0'}
iex(9)> Earmark.to_html ~s(```elixir\na=1\n```)
"<pre><code class=\"elixir\">a=1</code></pre>\n"
iex(10)> Earmark.to_html ~s{[MIT](LICENSE.md)}  
"<p><a href=\"LICENSE.md\">MIT</a></p>\n"
iex(11)> 
```

**Comment by seantanly** [comment]
When I ran mix docs, I get 

```
Failed to find closing <h2>
Failed to find closing <h2>
Failed to find closing <h2>
Failed to find closing <h2>
Failed to find closing <h2>
Docs successfully generated.
View them at "doc/index.html".
```

Could this be related? There isn't any of those warnings on 0.1.19.

**Comment by RobertDober** [comment]
That is something I have seen, meaning that some docs are just not correct markdown. I do not think it is related at all.

I'd love to help but I really do not see the issue here yet. Please provide a test case I can chew on.

BTW the HTML code you provided as an example was not generated by Earmark 0.19, is this correct?

**Comment by seantanly** [comment]
Here's one of the projects that I'm working on, which the error occurred. I had the same issue with another project.

https://github.com/seantanly/elixir-combination

Can you git clone it, change the mix.exs earmark version to 0.2.0 and run `MIX_ENV=docs mix docs` on it?

Thanks for taking the time to work on this. Really appreciate it. :)

**Comment by RobertDober** [comment]
that is a good idea, thx

**Comment by seantanly** [comment]
On a related note, the id or #anchors generated by earmark follows the capitalization of the headings, whereas GitHub lowercases all of them. 

Because of this capitalization disagreement, the intra-document links can't work on both github generated view of the markdown flies and the (hex)docs generated by earmark. We had to choose one or the other.

I would very much appreciate if earmark can generate the same <a>nchors Github does. :)

**Comment by RobertDober** [comment]
I reproduced the problem, finally :)
Thanx for reporting this.

Concerning the anchors I am not sure yet, but you might want to check this issue out https://github.com/elixir-lang/ex_doc/issues/508

**Comment by seantanly** [comment]
> I reproduced the problem, finally :)
Great! :)

As for elixir-lang/ex_doc#508 it's not really the same issue. Allow me to clarify.

Earmark is already generating the id for the headings, just not agreeing with GitHub on the capitalization. GitHub lowercases the entire id while Earmark maintains the capitalization. Therefore the same URL #fragment can't work for both.

For example, https://github.com/seantanly/elixir-combination which displays the README.md. The generated link for the Example link is 

https://github.com/seantanly/elixir-combination#Examples 

which wouldn't work on the GitHub page because GitHub generated the subheading Example with anchor #example instead of #Example. 

However it would work in the doc/readme.html because Earmark generates the id as #Example. 

I'm proposing Earmark to generate the ids in the same way as GitHub for the URL fragments to work in both situations.

**Comment by RobertDober** [comment]
Thx for the explication. Would you care to open an issue?

**Comment by seantanly** [comment]
Sure!

Previously I was confused that Earmark is generating the id attributes for the headers. Upon closer inspection at the output/code, I realized ex_doc is responsible for that. 

I'll open this issue on ex_doc. Thanks.

**Comment by seantanly** [comment]
Raised this on pull request https://github.com/elixir-lang/ex_doc/pull/510

**Comment by seantanly** [comment]
Thanks for releasing 0.2.1 which fixed the problem. :)

**Comment by RobertDober** [comment]
So this was already fixed, I did not do anything. Must have been a consequence of #56. The thank you for the release goes to @pragdave

**Comment by seantanly** [comment]
@pragdave Thanks! :)
