### ISSUE TITLE
Embedded img tags (maybe all self closing/void tags) aren't handled

### ISSUE THREAD

**Issue by mikekreuzer** [pragdave/earmark#61]
eg `<img src="whatevs.png"></img>` works, but `<img src="whatevs.png">` is valid html, but fails

**Comment by RobertDober** [comment]
You are making a valid point, need to check this out before deciding on implementation. Of course that concerns all void tags. According to the HTML5 spex we are accepting the incorrect format and refute the correct one (https://www.w3.org/TR/html5/syntax.html#void-elements). Again this cannot be totally fixed for backwards compatibility before a major release. 

However the goal would be to accept the correct void element form as a first step.
Thanx for pointing this out in any case.
Cheers
Robert

**Comment by RobertDober** [comment]
@mikekreuzer Thank you Mike for your empathy on #62. However I had some time to "fix" this one, I guess. So before merging the branch I thought I ask your opinion on this one, and Dave's too.

1. There was not really any problem with the generated HTML just an incorrect error message, do you agree?

1. I got rid of the error message for the tags which make "sense" in Markdown, like `img`, `hr` and so on, but not for `embed`, `link` and similar.

1. I guess we do not really need to warn about the old "incorrect" usage as we still accept it. And always will in this version at least. I feel that  the attitude "be lenient with your input but strict with your output" should apply.

1. ... and therefore in a near future could maybe get rid of the incorrect end tags.

Thx for your feedback

**Comment by mikekreuzer** [comment]
Sorry slow reply (I broke my arm & keeping up the pace is trickier than usual.)

1. No - when I got an error to standard out I also got markdown as output, not html. Just tested that with 1.2.3 and while:

`markdown = "<img></img>\n\nsome other stuff"`
`IO.puts "----"`
`html = Earmark.to_html(markdown)`
`IO.puts "----"`
`IO.puts html`

gives:
`----`
`----`
 `<img></img><p>some other stuff</p>`

if I drop the closing img tag & I get:

`----`
`Failed to find closing <img>`
`----`
`<img>`

`some other stuff`

**Comment by RobertDober** [comment]
Sorry for the arm, it is a hassle, I know, hope it's healing fast

Thx for your input, I see now how the html is incorrect

branch **master**:

```elixir
iex(3)>  Earmark.to_html ~s{<img src="alpha">\n __hello__}
Failed to find closing <img>
"<img src=\"alpha\">\n __hello__\n"
iex(4)>  Earmark.to_html ~s{<img src="alpha"></img>\n __hello__}
"<img src=\"alpha\"></img><p> <strong>hello</strong></p>\n"

```

unfortunately my bugfix is not complete yet as

branch **61-void-elements**

```elixir
iex(1)> Earmark.to_html ~s{<img src="alpha"></img>\n __hello__}
"<img src=\"alpha\"></img><p> <strong>hello</strong></p>\n"
iex(2)> Earmark.to_html ~s{<img src="alpha">\n __hello__}      
"<img src=\"alpha\">\n __hello__\n"
```

only got rid of the error message ;(

Hopefully finding some time next week...
