### ISSUE TITLE
Possible enhancement? Maybe have a bang version and a regular error returning version

### ISSUE THREAD

**Issue by mikekreuzer** [pragdave/earmark#62]
Maybe the current version could be a bang function, and we could also have something that reported errors?

`current_result = Earmark.to_html! content`
`{:ok, result} = Earmark.to_html content`

etc
cheers, and ta for your work on this from someone who's been looking at Elixir for all of minutes! Mike

**Comment by RobertDober** [comment]
The idea pleases me, however that kind of backward incompatible change cannot be done without a major release. For that reason I will need to have to wait for Dave to give me a green light for a major release. Given the current activity that seems unlikely in the near future though.

Maybe I can add a different method but that would be less idiomatic. An option could do a smooth transition to a next version though:

```elixir
   {:ok, result} = Earmark.to_html content, with_status: true # defaults to false in 0.x and will default to true in 1.x
```
Of course adding the bang version is a no brainer.

Any thoughts?

**Comment by pragdave** [comment]
Maybe leave the existing, but start warning that it is deprecated. Add two
new calls: as_html and as_html!.

Dave
​

**Comment by RobertDober** [comment]
Agreed

**Comment by RobertDober** [comment]
Actually this is quite a rewrite. I am thinking about changing Earmark.Line to Earmark.Token and to split lines up into tokens, writing rather a lexer, for some time now. Seems that this change would benefit of such a redesign but I have not thought it through to the end yet.

**Comment by mikekreuzer** [comment]
From little things big things grow. :-)

**Comment by RobertDober** [comment]
Having taken on new professional responsibilities I have much less time for Earmark now ;(. So I will concentrate on bugfixes and smaller issues.

**Comment by mikekreuzer** [comment]
No worries, so it goes.

**Comment by mikekreuzer** [comment]
:-)
