### ISSUE TITLE
What's the holdup on 1.0.0?

### ISSUE THREAD

**Issue by crertel** [pragdave/earmark#71]
So, what's left to get this to 1.0.0?

It's a little worrying to see such a widely-used package that is still nominally in pre-release status.

**Comment by RobertDober** [comment]
I closed this issue because I do not want an open issue which is not going to be "fixed". Now if @pragdave wants to answer your question he still can.

**Comment by crertel** [comment]
@RobertDober I disagree that this issue can't be "fixed".

If we can identify a set of release criteria (say, docs, test coverage, whatever), then we can start work on those, get a PR that works, bump the issue, cut the release on Hex, and *then* close the issue.

**Comment by pragdave** [comment]
I personally don't see a compelling need to make a 1.0 release, as I don't
see it making any difference in terms of use.

Remember, 0.x is not prerelease. Computer folk always count from 0 :)

**Comment by whatyouhide** [comment]
Just to give more context to this (even if I'm not a part of the development of earmark, just chiming in here 😃): quoting from [semver.org](http://semver.org):

> * Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.
> * Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it changes.

**Comment by pragdave** [comment]
Ah, good point.

I'm cool with it going to 1.0, but I'd ask Robert to handle the timing.


Dave

**Comment by RobertDober** [comment]
Just as a side note. We are very concerned about API stability inside 0.x.* and I really feel that this is commonly expected from 0.x releases all over OSS.

**Comment by crertel** [comment]
Thanks folks! I'm happy to help if there's any scut work you need done (docs, tests, whatever).

**Comment by RobertDober** [comment]
@crertel I was thinking for quite some time to have a test suit that assures the same behavior on some large input files, ideally some ex_doc input from important Elixir projects as Elixir, hex, phoenix you name it. Earmark has quite a complete test suite so maybe this could go somewhere else.
E.g. a github project called something like EarmarkNonreg.
This can become difficult if we compare naively we would need to compare the generated output structurally.
I'd also seek Dave's ok for this of course.

**Comment by crertel** [comment]
You could probably do something using one of the headless browsers setups...it's probably easiest just to compare to see if the generated DOM trees are identical.

**Comment by pragdave** [comment]
the dom trees won't be identical if we use different tags and attributes....

**Comment by crertel** [comment]
Ah, sorry--I figured the point was to duplicate the trees from the common mark tests. :)

**Comment by RobertDober** [comment]
DOM tree comparison would take us a long way though. I have some difficulty to imagine that the DOM tree will change a lot with bug fixes and new features. Small changes might easily be changed manually in the test suite. Concerning rendering that might be a future improvement when/if we find the correct tools.

**Comment by RobertDober** [comment]
So finally I started working on the test suite https://github.com/RobertDober/Earsuite

**Comment by crertel** [comment]
Yay! Need help?

**Comment by RobertDober** [comment]
@crertel sure, with pleasure
