### ISSUE TITLE
Wrong quotes in links

### ISSUE THREAD

**Issue by mschae** [pragdave/earmark#72]
Hey Dave,

possibly related to #26:

When using quotes inside of a link, they come out as both backwards. The first one should be forward:

Correct:
```elixir
Earmark.to_html ~s{"Earmark"}
# "<p>“Earmark”</p>\n"
```

vs. wrong:

```elixir
Earmark.to_html ~s{["Earmark"](https://github.com/pragdave/earmark/)}
# "<p><a href=\"https://github.com/pragdave/earmark/\">”Earmark”</a></p>\n"
```

Thanks

**Comment by mschae** [comment]
Thanks so much for fixing this a while ago! Any ETA on when to expect 1.0?

**Comment by RobertDober** [comment]
@mschae unfortunately not yet, I will try to get through to @pragdave for a release, master is ready for 1.0.0 so I hope he will find time soon.

**Comment by pragdave** [comment]
Oh, sorry.

I hadn't realized. I still saw some activity.

Is it ready to go now?

**Comment by RobertDober** [comment]
No problem Dave. Yes we are ready. The open issues will have to wait :). Thank you

**Comment by pragdave** [comment]
'tis done.

Robert—thank you so much for shepherding the code to this point. It would
not have got here without all your hard word.


Dave

**Comment by crertel** [comment]
Thanks again fellas!
