### ISSUE TITLE
Missing backquotes in Elixir Project not giving the right context

### ISSUE THREAD

**Issue by eksperimental** [pragdave/earmark#77]
related to #66 
I'm running against Elixir master (v1.4.0-dev) 
https://github.com/elixir-lang/elixir/tree/226438f68b0c2438345f7db72a3e8033d29173b2

You will get three errors when you run `make docs_elixir`

```
<no file>:42: warning: Closing unclosed backquotes ` at end of input
<no file>:392: warning: Closing unclosed backquotes ` at end of input
<no file>:36: warning: Closing unclosed backquotes ` at end of input
```

and there is no way I can figure out where the error is happening.
by running a regular expression, I found an offending line

https://github.com/elixir-lang/elixir/blob/226438f68b0c2438345f7db72a3e8033d29173b2/lib/elixir/lib/module.ex#L372

which is the one causing this warning
> <no file>:392: warning: Closing unclosed backquotes ` at end of input

So the line number is off by 20

the other two I don't know which one are.

**Comment by RobertDober** [comment]
I guess it is what I explained in #66, but maybe I am wrong. I can only count the lines in the block which is passed to `Earmark.to_html` which is *not* the entire file, correct? So I would need a start line in %Options{} to be passed in. I had a quick lock into `ex_doc` not a trivial thing but possible for sure (but ex_doc will become less converter agnostic). I apologize for bad communication here, I would love to discuss the issue on ex_doc, do you think it is ok to open an issue there?

**Comment by RobertDober** [comment]
Need to add the `%Options{start_linenumber}` in order to allow the implementation of https://github.com/elixir-lang/ex_doc/issues/561to be possible.

**Comment by RobertDober** [comment]
@pragdave I believe this should go into 1.0.0, this must be nerving on large code bases.

**Comment by eksperimental** [comment]
thank you @RobertDober for looking after this issue.

**Comment by eksperimental** [comment]
Indeed @RobertDober, it certainly is!
