### ISSUE TITLE
Indented fenced code blocks misindented

### ISSUE THREAD

**Issue by RobertDober** [pragdave/earmark#85]
Issue for

https://github.com/pragdave/earmark/pull/84

Mainly to have a regression test for the PR.

**Comment by jonnystorm** [comment]
Submitted for your approval: regression tests in https://github.com/pragdave/earmark/pull/84/commits/63ccc36baa31beb739359f9fc152dfe4a270e9b9.

**Comment by RobertDober** [comment]
wontfix is for v1 of Earmark, in v2 it might be easier to implement this.
