### ISSUE TITLE
Anchor links inside parenthesis

### ISSUE THREAD

**Issue by milmazz** [pragdave/earmark#88]
Working on a new feature for `ex_doc` I notice the following behavior with Earmark:

```bash
$ iex -S mix
iex(1)> Earmark.to_html("(the same ones accepted by [configure/1](#configure/1))")
"<p>(the same ones accepted by <a href=\"#configure/1)\">configure/1</a></p>\n"
```

When the expected result is: `<p>(the same ones accepted by <a href=\"#configure/1\">configure/1</a>)</p>`

Doing the same thing with [Markdown](https://github.com/devinus/markdown) produce the following result:

```bash
$ iex -S mix
iex(1)> Markdown.to_html "(the same ones accepted by [configure/1](#configure/1))"
"<p>(the same ones accepted by <a href=\"#configure/1\">configure/1</a>)</p>\n"
```

Another example can be found in [ExUnit.html#start/1](http://elixir-lang.org/docs/master/ex_unit/ExUnit.html#start/1)

**Comment by RobertDober** [comment]
Thanks for the report. For the record the minimal input triggering the bug
```iex
Earmark.to_html("([]())")
"<p>(<a href=\")\"></a></p>\n"
```

**Comment by RobertDober** [comment]
Hmm maybe a different bug, we will see
http://johnmacfarlane.net/babelmark2/?text=%5B%5Btext%5D(link)%5D

**Comment by milmazz** [comment]
@robertdober I think is this one:

http://johnmacfarlane.net/babelmark2/?text=(%5Btext%5D(link))

**Comment by RobertDober** [comment]
@milmazz yep that is the original one, http://johnmacfarlane.net/babelmark2/?text=%5B%5Btext%5D(link)%5D seems very much related, not sure yet though
