### ISSUE TITLE
Link inside brackets not recognized

### ISSUE THREAD

**Issue by RobertDober** [pragdave/earmark#89]
http://johnmacfarlane.net/babelmark2/?text=%5B%5Btext%5D(link)%5D should be converted to a link

**Comment by RobertDober** [comment]
However parsing
```[text(inner)](outer)```
http://johnmacfarlane.net/babelmark2/?normalize=1&text=%5B%5Btext%5D(inner)%5D(outer)
can be interpreted as
```html
<p><a href="outer">[text](inner)</a>
</p>
```

and is so by 17 babelmark converters or as

as (the unfortunate)
```html
<p><a href="outer"><a href="inner">text</a></a>
</p>

```
and is so by Earmark 1.0.1 and 4 other converters, or as

```html
<p>[<a href="inner">text</a>](outer)</p>
```

and is so by 5 converters.

I tend to agree with the majority.

**Comment by RobertDober** [comment]
oh I added issue so the automatic close did not work

**Comment by shisongsong** [comment]
I got the same problem,  how about now? 
How to make it work

**Comment by RobertDober** [comment]
Actually the behavior now is what we want
``` Interactive Elixir (1.5.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Earmark.as_html("[text(inner)](outer)")
{:ok, "<p><a href=\"outer\">text(inner)</a></p>\n", []}
iex(2)>
``` 
maybe just upgrade?
