### ISSUE TITLE
Opening html tag at the beginning of line closes paragraph

### ISSUE THREAD

**Issue by sickill** [pragdave/earmark#95]
iex(1)> Earmark.to_html("foo\nbar baz")
    "<p>foo\nbar baz</p>\n"
    iex(2)> Earmark.to_html("foo\n<b>bar</b> baz")
    "<p>foo</p>\n<b>bar</b> baz"
    iex(3)> Earmark.to_html("foo\nand <b>bar</b> baz")
    "<p>foo\nand <b>bar</b> baz</p>\n"

Result 1 and 3 are correct, however 2 doesn't seem to be. It shouldn't(?) close `<p>` before `<b>` (at least this is how other markdown parsers behave).

**Comment by RobertDober** [comment]
Thanx for the report, nice catch.

**Comment by sickill** [comment]
@RobertDober I used a workaround (moving last word from prev line in my text to the beginning of the line with tag). Fortunately I fully control the markdown text here, and it was the only place where it bite me so no rush.

**Comment by RobertDober** [comment]
@sickill appreciated
