### ISSUE TITLE
Prism.js compatibility for `code` blocks in specific languages

### ISSUE THREAD

**Issue by campezzi** [pragdave/earmark#96]
[Prism.js](http://prismjs.com/) expects code blocks for a specific language to have a class of `language-some_language_name`, for example `language-elixir`. By default, Earmark's `HtmlRenderer` module creates those blocks with a class that does not contain the `language-` prefix. I have worked around this by defining a custom `PrismRenderer` module which is essentially a copy/paste of `HtmlRenderer` with that minor change applied, but it obviously feel dirty :)

I understand modifying Earmark to be Prism-compliant is not the right thing to do, but is there a way of accomplishing this that does not involve duplicating all the code in `HtmlRenderer`?

Would it be a good idea to release a `earmark_prism_renderer` package that only includes that? I'm thinking of doing that but happy to hear from the experts.

**Comment by RobertDober** [comment]
I would not do that for the simple reason that you would need to follow up on each bug fix. And the approach per se would mean that there would be n earmark_youknow_it renderers out there.

I believe that the Prism use case is quite common btw. Maybe we can just add an option like that

```elixir
     Earmark.to_html "```elixir\ndef the_answer...\n```", %Earmark.Options{language_prefix: "language-"}
```
and the according command line option of course.

Would that scratch your itch? It should be a very easy enhancement.

**Comment by campezzi** [comment]
Yup, I agree. The option approach would work for me - I thought about suggesting that, but I thought it could be a bit odd as that option only applies to the `HtmlRenderer`. If you feel like that's OK, I'd be glad to take a look and send a PR!

**Comment by RobertDober** [comment]
@campezzi great.

 FYI, many if not most options are used by the renderer, e.g. `gfm`, `smartypants`.

**Comment by RobertDober** [comment]
@campezzi I do not want to push you, only wanted to know if you are working on a PR.
If not let me know please I will implement this enhancement as I believe it is quite valuable.
But I just do not want to step on your toes.

**Comment by campezzi** [comment]
Ended up getting flooded in other projects and pushed this down on the priority list. If you think it's an important feature to have right away, go for it! I'll only have time to revisit it in a couple of weeks or so. Thanks for asking though!

**Comment by RobertDober** [comment]
@campezzi thx for your feedback. I'll assign it to myself and hopefully will get it done soon.
