### ISSUE TITLE
wrongly convert links when "))" is used

### ISSUE THREAD

**Issue by eksperimental** [pragdave/earmark#97]
```
(such as [`Enum.t`](Enum.html#t:t/0)).
```
generates

```html
<p>(such as <a href="Enum.html#t:t/0)"><code class="inline">Enum.t</code></a>.</p>
```

when it should be
```html
<p>(such as <a href="Enum.html#t:t/0"><code class="inline">Enum.t</code></a>).</p>
```

**Comment by RobertDober** [comment]
@eksperimental thanx for the report, this was fixed with #88 and shall be released soon.

**Comment by eksperimental** [comment]
Thank u Robert

**Comment by RobertDober** [comment]
FYI The release is ready hopefully Dave finds some time soon :)

**Comment by pragdave** [comment]
Et voilà!  v1.0.2 is published.

Thank you so much Robert for shouldering the work on this.


Dave

**Comment by RobertDober** [comment]
Merci beaucoup Dave :smile:
