### ISSUE TITLE
Tuple with atom breaks conversion

### ISSUE THREAD

**Issue by milmazz** [pragdave/earmark#99]
How to reproduce this error:

```iex
iex(1)> Earmark.to_html(~S({:hello}))
```

**Comment by RobertDober** [comment]
That one hurts, thanks for the report.
Tech note: Happens only if tuple is alone in line (ignoring ws) and atom is first.

**Comment by RobertDober** [comment]
@milmazz if you need an (ugly) workaround you can put a space between { and : 
```
iex(2)> Earmark.to_html "{ :hello} "
"<p>{ :hello} </p>\n"
iex(3)>
```

**Comment by RobertDober** [comment]
@pragdave personally I like IALs (used them with Kramdown several years ago). However Kramdown and Maruku are the only implementations on Babelmark to implement them. Do you want me to implement them or to remove them?

**Comment by milmazz** [comment]
@RobertDober Thanks for taking care of this, I'll try to put this temporary workaround in the [conversion process of the Elixir Getting Started Guide to EPUB](https://github.com/elixir-lang/elixir-lang.github.com/issues/860). Thanks!

**Comment by pragdave** [comment]
I don't think so. I like them, and there are many other constructs that
would "break" the conversion (such as starting a paragraph with an
asterisk).

However, it shouldn't crash the conversion the way it does. Perhaps if the
thing inside the IAL isn't handled, we could revert to treating it as plain
text?

**Comment by RobertDober** [comment]
@pragdave happy to implement rendering IALs and eliminating the crash of course. @milmazz that will not be a workaround then. Although I guess that we will render your use case as text ultimately I suggest you use the escaped syntax because the rendering of `{:text}` will become error prone as depending on the context...

As IALs are so uncommon I will definitely update the README. I might need some help correcting my English on that one though 😢

**Comment by RobertDober** [comment]
@pragdave you might want to check the README changes; I tried to write simple English, but...

**Comment by pragdave** [comment]
You are talking with the person who in a school French exam translated *cane
à pêche*
as *tin of peaches*.  Your English is phenomenal.

I pushed some trivial updates.

Thanks again for everything.
